ForServiceName added to Jupyter, Wordpress, and Jenkins
google/tsunami-security-scanner-plugins pull request #15
Opened 2020-09-17 15:23 UTC by truttruthahnhahn

This pull request fixes issue #5 by adding http and https ForServiceName annotations to Jenkins, Wordpress, and Jupyter plugins.

According to the documentation, "https" is the right service name, although nmap lists "ssl/ssl" for https ports scanned by us.
We could not test this because of issue #7, where https services are recognized as http.

2020-09-24 08:13 UTC, truttruthahnhahn commented
@googlebot I signed it!

2020-12-16 16:41 UTC, erikvarga requested changes

2020-12-16 16:41 UTC, erikvarga commented on google/detectors/exposedui/jenkins/src/main/java/com/google/tsunami/plugins/detectors/exposedui/jenkins/JenkinsExposedUiDetector.java
> +@ForServiceName({"http","https"})
Please add a whitespace after the comma (also in the other two files)

2021-02-24 17:42 UTC, magl0 commented on google/detectors/exposedui/jenkins/src/main/java/com/google/tsunami/plugins/detectors/exposedui/jenkins/JenkinsExposedUiDetector.java
> +@ForServiceName({"http","https"})
Alternatively you can use the `@ForWebService` [annotation](https://github.com/google/tsunami-security-scanner/blob/master/plugin/src/main/java/com/google/tsunami/plugin/annotations/ForWebService.java) rather than listing all the potential service names here.

2021-02-26 19:45 UTC, gaby commented
Ths PR can now close since #17 was merged

2021-02-27 09:26 UTC, closed without merging