Adds a detector for Apache Struts Command Injection via Content-Type Header (CVE-2017-5638)
google/tsunami-security-scanner-plugins pull request #16
Opened 2020-11-02 16:02 UTC by mtrzos

2020-11-02 17:21 UTC, mtrzos commented on google/detectors/rce/CVE-2017-5638/src/main/java/com/google/tsunami/plugins/detectors/rce/CVE-2017-5638/ApacheStrutsContentTypeRceDetector.java
> +  static final String RANDOM_VALUE = "IhEmKCn1Lqa79o2mXmAsIzBfcMojgseiOd7srLNFlPZmzqWkRaiQNZ89mZywYLBx";
We decided to hardcode the "random" value to avoid extra complexity in tests where we have to parse the header, extract the random value and return it so that the unit test passes. I have also not found easy ways of injecting random interfaces.

2020-11-02 17:55 UTC, mtrzos commented
This has also been tested locally with the Tsunami Engine on a vulnerable application exposed by the Docker image: https://hub.docker.com/r/piesecurity/apache-struts2-cve-2017-5638/

2020-11-03 00:37 UTC, magl0 requested changes

2020-11-03 00:37 UTC, magl0 commented on google/detectors/rce/CVE-2017-5638/README.md
> +This checks if an Apache Struts application is vulnerable to Command Injection
nit: Text files may not contain trailing whitespace

2020-11-03 00:37 UTC, magl0 commented on google/detectors/rce/CVE-2017-5638/src/main/java/com/google/tsunami/plugins/detectors/rce/CVE-2017-5638/ApacheStrutsContentTypeRceDetector.java
> +    description = "Tsunami detector plugin for Apache Struts Command Injection via Content-Type header (CVE-2017-5638).",
nit: max line width: 100. ditto for the remaining of this file and the unittest.

2020-11-03 00:37 UTC, magl0 commented on google/detectors/rce/CVE-2017-5638/src/main/java/com/google/tsunami/plugins/detectors/rce/CVE-2017-5638/ApacheStrutsContentTypeRceDetector.java
> +                .setCvssV3("10.0")
I think you can omit these values for now until we found a canonical way of handling CVSS scores and vectors in Tsunami.

2020-11-03 00:37 UTC, magl0 commented on google/detectors/rce/CVE-2017-5638/src/test/java/com/google/tsunami/plugins/detectors/rce/CVE-2017-5638/ApacheStrutsContentTypeRceDetectorTest.java
> +;
Remoe these lines.

2020-11-03 00:37 UTC, magl0 commented on google/detectors/rce/CVE-2017-5638/src/test/java/com/google/tsunami/plugins/detectors/rce/CVE-2017-5638/ApacheStrutsContentTypeRceDetectorTest.java
> +                            "Apache Struts Command Injection via Content-Type header (CVE-2017-5638)")
nit: max line width 100.

2020-11-03 06:38 UTC, mtrzos commented on google/detectors/rce/CVE-2017-5638/README.md
> +This checks if an Apache Struts application is vulnerable to Command Injection
Done

2020-11-03 06:38 UTC, mtrzos commented on google/detectors/rce/CVE-2017-5638/src/main/java/com/google/tsunami/plugins/detectors/rce/CVE-2017-5638/ApacheStrutsContentTypeRceDetector.java
> +    description = "Tsunami detector plugin for Apache Struts Command Injection via Content-Type header (CVE-2017-5638).",
Done

2020-11-03 06:38 UTC, mtrzos commented on google/detectors/rce/CVE-2017-5638/src/main/java/com/google/tsunami/plugins/detectors/rce/CVE-2017-5638/ApacheStrutsContentTypeRceDetector.java
> +                .setCvssV3("10.0")
Done

2020-11-03 06:38 UTC, mtrzos commented on google/detectors/rce/CVE-2017-5638/src/test/java/com/google/tsunami/plugins/detectors/rce/CVE-2017-5638/ApacheStrutsContentTypeRceDetectorTest.java
> +                            "Apache Struts Command Injection via Content-Type header (CVE-2017-5638)")
Done

2020-11-03 06:59 UTC, mtrzos commented on google/detectors/rce/CVE-2017-5638/src/test/java/com/google/tsunami/plugins/detectors/rce/CVE-2017-5638/ApacheStrutsContentTypeRceDetectorTest.java
> +;
Done

2020-11-03 17:12 UTC, merged