Spring CVE 2022 22965
google/tsunami-security-scanner-plugins pull request #237
Opened 2022-04-02 08:02 UTC by C4o

Hi @magl0 , I have completed the detector of CVE-2022-22965, please review it. Thanks!

This vulnerability can be used to write webshell, so I try to write a specific harmless string to a specific file, after it's verified, clear the `class.module.classLoader.resources.context.parent.pipeline.first.pattern`, because every request logging will be written into that file. 

The vulnerable docker and the way to clear is from [vulhub](https://github.com/vulhub/vulhub/tree/master/spring/CVE-2022-22965), and the fixed docker is based on it too.

isseue: #235 

vulnerable docker

```
version: '2'
services:
 spring:
   image: vulhub/spring-webmvc:5.3.17
   ports:
    - "8889:8080"
```

fixed docker

```
version: '2'
services:
 spring:
   image: levi4/spring-webmvc:5.3.18
   ports:
    - "8889:8080"
```

2022-04-02 10:47 UTC, hh-hunter commented on community/detectors/spring_framework_cve_2022_22965/src/main/java/com/google/tsunami/plugins/detectors/spring/SpringCve202222965Detector.java
> +  private static final String VULNERABILITY_PAYLOAD_STRING = "class.module.classLoader.resources."
Are you sure? You're going to attack the site directly like that, causing the logging function to fail and there's a backdoor left over? Are you sure you want to test like that?

2022-04-02 10:47 UTC, hh-hunter commented on community/detectors/spring_framework_cve_2022_22965/src/main/java/com/google/tsunami/plugins/detectors/spring/SpringCve202222965Detector.java
> +    String targetUri = NetworkServiceUtils.buildWebApplicationRootUrl(networkService);
This way of checking will miss the point of vulnerability, are you sure you really understand how the vulnerability is triggered? And the conditions under which the vulnerability is triggered?

2022-04-02 16:35 UTC, C4o commented on community/detectors/spring_framework_cve_2022_22965/src/main/java/com/google/tsunami/plugins/detectors/spring/SpringCve202222965Detector.java
> +  private static final String VULNERABILITY_PAYLOAD_STRING = "class.module.classLoader.resources."
Thanks for your useful advice! I've repalced my payload with a more harmless one  and changed code to use crawler to get more potential point. Could you review my code again?

BTW, have you recently joined Google? Cause it was magl0 reviewing code before.

2022-04-04 20:45 UTC, magl0 requested changes

2022-04-04 20:45 UTC, magl0 commented on community/detectors/spring_framework_cve_2022_22965/README.md
> +without authentication, causing information leakage.
Please update the descriptions :)

2022-04-04 20:45 UTC, magl0 commented on community/detectors/spring_framework_cve_2022_22965/src/main/java/com/google/tsunami/plugins/detectors/spring/SpringCve202222965Detector.java
> +import static com.google.tsunami.common.data.NetworkEndpointUtils.toUriAuthority;
Please use the `google-java-format` [tool](https://github.com/google/google-java-format) to reformat this PR.

[Style comment](https://google.github.io/styleguide/javaguide.html#s3.3-import-statements): Imports are ordered as follows:

- All static imports in a single block.
- All non-static imports in a single block.

2022-04-04 20:45 UTC, magl0 commented on community/detectors/spring_framework_cve_2022_22965/src/main/java/com/google/tsunami/plugins/detectors/spring/SpringCve202222965Detector.java
> +    }
You don't need to perform your own crawling in the detectors. Tsunami's fingerprinter will populate all the crawling results into the [`NetworkService.service_context.web_service_context.crawl_results` field](https://github.com/google/tsunami-security-scanner/blob/master/proto/network_service.proto#L78).

2022-04-04 20:45 UTC, magl0 commented on community/detectors/spring_framework_cve_2022_22965/src/main/java/com/google/tsunami/plugins/detectors/spring/SpringCve202222965Detector.java
> +                .setDescription("A Spring MVC or Spring WebFlux application running on JDK"
Can you please also set the `recommendation` field so that the user receiving the report knows how to fix the issue?

2022-04-06 00:47 UTC, magl0 reviewed
Coding looks OK. One comment on the payload which doesn't need your immediate attention yet.

2022-04-06 00:47 UTC, magl0 commented on community/detectors/spring_framework_cve_2022_22965/src/main/java/com/google/tsunami/plugins/detectors/spring/SpringCve202222965Detector.java
> +      "class.module.classLoader.DefaultAssertionStatus=2";
There are discussions within the team about the payload. I'll update this thread in case this needs to be changed.

2022-04-06 04:16 UTC, C4o commented on community/detectors/spring_framework_cve_2022_22965/src/main/java/com/google/tsunami/plugins/detectors/spring/SpringCve202222965Detector.java
> +      "class.module.classLoader.DefaultAssertionStatus=2";
okay:)

2022-04-07 00:53 UTC, magl0 commented
This is sent to internal code review. It will be merged automatically upon internal approvals. Otherwise new comments will be added :-)

2022-04-11 23:35 UTC, merged