Roxy-wi CVE-2022-31137
google/tsunami-security-scanner-plugins pull request #314
Opened 2023-04-19 19:27 UTC by am0o0

https://github.com/google/security-testbeds/pull/105
https://github.com/google/tsunami-security-scanner-plugins/issues/309

2024-08-05 15:20 UTC, tooryx commented
Hi @am0o0, let's wait for https://github.com/google/tsunami-security-scanner-plugins/pull/369 to be merged. Sorry, we have a bit of backlog but we are trying to walk through it.

_~tooryx_

2024-09-12 13:43 UTC, tooryx commented
Hi @am0o0,

If you have AI related plugin that you would like to work on, feel free to suggest them. AI plugin are parallel to the contributor queue. That being said, even if this specific plugin was requested by @maoning, it does not change the fact that we have to go through the backlog. We are working through it but it takes time, that does not mean that we are not interested.

_~tooryx_

2024-11-26 20:11 UTC, lokiuox commented
Hi @am0o0 , could you please provide a testbed for this plugin?

2024-12-09 17:07 UTC, giacomo-doyensec commented
Additionally, the plugin is missing the fingerprint phase. Could you please add it?

2024-12-10 18:29 UTC, giacomo-doyensec requested changes
Thanks @am0o0!
You can find some comments and suggestion down below. 
Please remember to update the testbed reproduction steps when making changes at the detector logic and to run the `google-java-format` tool before pushing your changes.

2024-12-10 18:29 UTC, giacomo-doyensec commented on community/detectors/roxy_wi_cve_2022_31137/README.md
> +Roxy-WI is a web interface for managing Haproxy, Nginx, Apache and Keepalived servers. Versions prior to 6.1.1.0 are subject to a remote code execution vulnerability. System commands can be run remot
```suggestion
Roxy-WI is a web interface for managing Haproxy, Nginx, Apache and Keepalived servers. Versions prior to `6.1.1.0` are subject to a remote code execution vulnerability. System commands can be run remotely via the `subprocess_execute` function without processing the inputs received from the user in the /app/options.py file. Authentication is not required to exploit this vulnerability. Users are advised to upgrade. There are no known workarounds for this vulnerability.
```

2024-12-10 18:29 UTC, giacomo-doyensec commented on community/detectors/roxy_wi_cve_2022_31137/src/main/java/com/google/tsunami/plugins/detectors/cves/cve202231137/Cve202231137Detector.java
> +      "alert_consumer=1&serv=127.0.0.1&ipbackend=\";%s+##&backend_server=127.0.0.1";
I was able to reproduce the vulnerability using only these parameters: `alert_consumer` and `ipbackend`. Can the others be removed or is there a reason to keep them?
The only difference I noticed is that the response contains a trailing `<br>` when omitting the `backend_server` parameter. 

You can try this with the following command against the [relative vulnerable testbed](https://github.com/google/security-testbeds/pull/105):
`curl -X POST "https://localhost/app/options.py" --data "alert_consumer=1&ipbackend=\";id+#" --insecure`

```suggestion
      "alert_consumer=1&ipbackend=\";%s+#";

```

2024-12-10 18:29 UTC, giacomo-doyensec commented on community/detectors/roxy_wi_cve_2022_31137/src/main/java/com/google/tsunami/plugins/detectors/cves/cve202231137/Cve202231137Detector.java
> +        || isVulnerableWithoutCallback(networkService);
Why is the double detection needed at all?
I would prioritize the execution of `isVulnerableWithoutCallback` to not waste time during the scan. If you can confirm that this method is enough for the detection it would be best if the plugin could generate a value that gets reflected at runtime, to be sure that the output isn't faked; something like `echo "randval1"\$(id)"randval2"` generates the following reflection: `rand1<id output>rand2` and would be sufficient, in my opinion, to confirm the vulnerability.

2024-12-10 18:29 UTC, giacomo-doyensec commented on community/detectors/roxy_wi_cve_2022_31137/src/main/java/com/google/tsunami/plugins/detectors/cves/cve202231137/Cve202231137Detector.java
> +          networkService);
While testing dynamically I noticed that these headers can be omitted, if you can confirm that they are not required, please remove this.
```suggestion

    String targetVulnerabilityUrl =
        NetworkServiceUtils.buildWebApplicationRootUrl(networkService) + VULNERABLE_REQUEST_PATH;
    try {
      return httpClient.send(
          post(targetVulnerabilityUrl)
              .setRequestBody(ByteString.copyFromUtf8(Payload))
              .build(),
          networkService);

```

2024-12-10 18:29 UTC, giacomo-doyensec commented on community/detectors/roxy_wi_cve_2022_31137/src/main/java/com/google/tsunami/plugins/detectors/cves/cve202231137/Cve202231137Detector.java
> +    } else return false;
These checks can be simplified as follows:

```suggestion
    if (response == null || response.bodyString().isEmpty()) {
      return false;
    }
  
    return payload.checkIfExecuted(response.bodyString().get());
```

2024-12-11 17:03 UTC, giacomo-doyensec commented on community/detectors/roxy_wi_cve_2022_31137/src/main/java/com/google/tsunami/plugins/detectors/cves/cve202231137/Cve202231137Detector.java
> +  private boolean isVulnerableWithoutCallback(NetworkService networkService) {
Please remove the `isVulnerableWithoutCallback` method and move the logic inside `isServiceVulnerable`

```suggestion
```

2024-12-12 08:47 UTC, giacomo-doyensec commented
**LGTM** - Approved
@maoning we can merge this and https://github.com/google/security-testbeds/pull/105

_Reviewer_: Giacomo, Doyensec
_Plugin_: CVE-2022-31137 - Roxy-wi RCE

2024-12-12 16:25 UTC, giacomo-doyensec commented on community/detectors/roxy_wi_cve_2022_31137/src/main/java/com/google/tsunami/plugins/detectors/cves/cve202231137/Cve202231137Detector.java
> +    return payload.checkIfExecuted(response.bodyString().get());
I'm sorry to reopen this as I had already marked it as LGTM but I just noticed that here the sleep must be put back inside an if that guards the instruction and checks if the payload is using OOB (something like `payload.getPayloadAttributes().getUsesCallbackServer()` should work). Tsunami generates reflective payloads only when callback server is not available so here we would miss the detection if it was configured. Please implement the sleep using  `sleepUninterruptibly` and the relative annotations.

2024-12-13 12:28 UTC, giacomo-doyensec requested changes
Hello @am0o0, thanks for the updates! I left two comments on your latest changes.

2024-12-13 12:28 UTC, giacomo-doyensec commented on community/detectors/roxy_wi_cve_2022_31137/src/main/java/com/google/tsunami/plugins/detectors/cves/cve202231137/Cve202231137Detector.java
> +    }
The payload can mutate based on the presence or absence of the callback server, please move the check as a guard of the sleep instruction.

```suggestion
```

2024-12-13 12:28 UTC, giacomo-doyensec commented on community/detectors/roxy_wi_cve_2022_31137/src/main/java/com/google/tsunami/plugins/detectors/cves/cve202231137/Cve202231137Detector.java
> +    return false;
Please wait for the callback only when the callback server is involved in the operation.

```suggestion
    if (payload.getPayloadAttributes().getUsesCallbackServer()) {
      logger.atInfo().log("Waiting for RCE callback.");
      Uninterruptibles.sleepUninterruptibly(Duration.ofSeconds(oobSleepDuration));
    }

    return payload.checkIfExecuted(response.bodyString().get());
```

2024-12-13 17:15 UTC, giacomo-doyensec commented
**LGTM** - Approved
@maoning we can merge this and google/security-testbeds#105

_Reviewer_: Giacomo, Doyensec
_Plugin_: CVE-2022-31137 - Roxy-wi

2025-02-10 16:00 UTC, tooryx commented
Hi @am0o0,

Sorry for the delay.
The test function `detect_whenVulnerable_returnsVulnerability` does not actually test that the behavior is the right one. For example, when simply adding the `assertThat(detectionReports.getDetectionReportsList()).hasSize(1);` pragma, the test fails.

Could you please fix it? Which means, ensuring that the detector returns the right detection report.

Thank you,
_~tooryx_

2025-02-11 10:23 UTC, tooryx commented
Thank you, the plugin is now being reviewed internally and should be merged in a few days.

_~tooryx_

2025-02-12 10:07 UTC, merged