add plugin CVE-2024-21650
google/tsunami-security-scanner-plugins pull request #387
Opened 2024-01-31 17:41 UTC by YuriyPobezhymov

Hey,

this PR for the Vuln Detector Plugin for https://nvd.nist.gov/vuln/detail/CVE-2024-21650 (see https://github.com/google/tsunami-security-scanner-plugins/issues/366)

In order to verify the vulnerability, I used two different docker environment types, one for the vulnerable version and the other for the fixed version.

To get them pls clone https://github.com/xwiki/xwiki-docker.git.
There are several versions of XWiki. I did use all of them for testing purpose. "15" folder contains latest one.

I can show you how to prepare it for testing:

    Go to folder with docker-compose.yml;
    There is file .env that we can modify for our purposes;
    Rename file to .env-true-negative;
    Create copy of file with .env-true-positive name;
    Change XWIKI_VERSION value there inside to vulnerable one - in my case to 15.7.0 in the current folder;

To run vulnerable version:
docker-compose --env-file .env-true-positive -p xwiki-true-positive up -d

Fixed version:
docker-compose --env-file .env-true-negative -p xwiki-true-negative up -d

2024-02-19 10:01 UTC, tooryx commented
hi @YuriyPobezhymov,

We are catching up with the backlog, but we are a limited number of people. Please bear with us, we are getting there.

_~tooryx_

2024-06-13 16:59 UTC, YuriyPobezhymov commented
@tooryx, why the PR is still pending? So long time ago...

2024-07-09 12:00 UTC, leonardo-doyensec commented
Hi @YuriyPobezhymov,
I'm noticing that you haven't linked the security testbed to this pull request. In order to have a complete plugin you must submit a pull request to https://github.com/google/security-testbeds. Ideally the testbed should list all the steps to create both the vulnerable container and the safe one in a clear way.

2024-07-09 16:08 UTC, YuriyPobezhymov commented
Ok, config added to the security testbed as [#69](https://github.com/google/security-testbeds/pull/69).

2024-08-16 19:43 UTC, lokiuox requested changes
Hey @YuriyPobezhymov, thanks for your contribution!

I've reviewed your plugin and I left some comments on things that can be improved.
Also, please don't forget to do the following:
- Fix the suggestions in the testbed PR
- Format all Java files with the google-java-format tool

2024-08-16 19:43 UTC, lokiuox commented on community/detectors/xwiki_cve_2024_21650/build.gradle
> +description = 'Tsunami Apache APISIX RCE (CVE-2022-24112) VulnDetector plugin.'
Fix the description to match this detector's name

2024-08-16 19:43 UTC, lokiuox commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650Detector.java
> +import com.google.tsunami.proto.*;
Please avoid using wildcard imports

2024-08-16 19:43 UTC, lokiuox commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650Detector.java
> +    description = "This detector checks user XWiki registration feature for RCE (CVE-2024-21650).",
```suggestion
    description = "This detector checks for XWiki RCE via user registration (CVE-2024-21650).",
```

2024-08-16 19:43 UTC, lokiuox commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650Detector.java
> +              && (payloadGenerator.isCallbackServerEnabled() && payload.checkIfExecuted())
Please add a few seconds of sleep time before checking if the payload was received, to ensure the exploit has time to run and the callback server has time to receive the callback.

You should use `sleepUninterruptibly` with an injected duration, so that you can set the sleep to 0 in the tests. Check out [this detector](https://github.com/google/tsunami-security-scanner-plugins/tree/master/community/detectors/argocd_exposed_ui/src/main/java/com/google/tsunami/plugins/detectors/exposedui/argocd) for an example on how to implement this correctly.

Specifically, check:
- [the place where the sleep is executed](https://github.com/google/tsunami-security-scanner-plugins/blob/74ebe7c8978c08d756b183e42bb8b192d890dcae/community/detectors/argocd_exposed_ui/src/main/java/com/google/tsunami/plugins/detectors/exposedui/argocd/ExposedArgoCdApiDetector.java#L363)
- [where the variable is injected](https://github.com/google/tsunami-security-scanner-plugins/blob/74ebe7c8978c08d756b183e42bb8b192d890dcae/community/detectors/argocd_exposed_ui/src/main/java/com/google/tsunami/plugins/detectors/exposedui/argocd/ExposedArgoCdApiDetector.java#L119)
- [the definition in the Annotations file](https://github.com/google/tsunami-security-scanner-plugins/blob/74ebe7c8978c08d756b183e42bb8b192d890dcae/community/detectors/argocd_exposed_ui/src/main/java/com/google/tsunami/plugins/detectors/exposedui/argocd/Annotations.java#L28)
- [the provider in the bootstrap](https://github.com/google/tsunami-security-scanner-plugins/blob/74ebe7c8978c08d756b183e42bb8b192d890dcae/community/detectors/argocd_exposed_ui/src/main/java/com/google/tsunami/plugins/detectors/exposedui/argocd/ExposedArgoCdApiDetectorBootstrapModule.java#L31)
- [And how to override it in the tests](https://github.com/google/tsunami-security-scanner-plugins/blob/74ebe7c8978c08d756b183e42bb8b192d890dcae/community/detectors/argocd_exposed_ui/src/test/java/com/google/tsunami/plugins/detectors/exposedui/argocd/ExposedArgoCdApiDetectorTest.java#L82)

2024-08-16 19:43 UTC, lokiuox commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650Detector.java
> +    }
```suggestion
    String requestBody = REQUEST_POST_DATA
            .replace("{{PAYLOAD}}", cmd)
            .replace("{{TOKEN}}", token);
```

Since there are only two values to replace, I think it's easier to just do two replace operations instead of a loop.

2024-08-16 19:43 UTC, lokiuox commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650Detector.java
> +      "rest/wikis/xwiki/spaces/XWiki/pages/" + REQUEST_USER_NAME + "/objects/XWiki.XWikiUsers/0";
Since these are not really constants, I think it would be better to make them normal instance fields (or even just local function variables). (Except for `CSRF_TOKEN_PATTERN`)

2024-08-17 16:36 UTC, YuriyPobezhymov commented on community/detectors/xwiki_cve_2024_21650/build.gradle
> +description = 'Tsunami Apache APISIX RCE (CVE-2022-24112) VulnDetector plugin.'
Oops, updated

2024-08-17 16:38 UTC, YuriyPobezhymov commented on community/detectors/xwiki_cve_2024_21650/build.gradle
> +    junitVersion = '4.13'
changed to tsunamiVersion = 'latest.release'
junitVersion version updated
guice deps added for OOB testing

2024-08-17 16:39 UTC, YuriyPobezhymov commented on community/detectors/xwiki_cve_2024_21650/build.gradle
> +    testImplementation "com.squareup.okhttp3:mockwebserver:${okhttpVersion}"
unused deps removed

2024-08-17 16:40 UTC, YuriyPobezhymov commented on community/detectors/xwiki_cve_2024_21650/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip
done

2024-08-17 16:40 UTC, YuriyPobezhymov commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650Detector.java
> +import com.google.tsunami.proto.*;
imports expanded now

2024-08-17 16:41 UTC, YuriyPobezhymov commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650Detector.java
> +    description = "This detector checks user XWiki registration feature for RCE (CVE-2024-21650).",
correction applied

2024-08-17 16:42 UTC, YuriyPobezhymov commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650Detector.java
> +              && (payloadGenerator.isCallbackServerEnabled() && payload.checkIfExecuted())
done, pls check if it's ok on you side

2024-08-17 16:42 UTC, YuriyPobezhymov commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650Detector.java
> +    }
agree, applied

2024-08-17 16:47 UTC, YuriyPobezhymov commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650Detector.java
> +      "rest/wikis/xwiki/spaces/XWiki/pages/" + REQUEST_USER_NAME + "/objects/XWiki.XWikiUsers/0";
I use such constants decomposition for better readability for those researchers who will work with that in future.
I think that they are contants as never change there values in future even they have been init by others.
Pls share you thoughts with me, possibly I didn't get understandings.

2024-08-17 16:48 UTC, YuriyPobezhymov commented
- Fix the suggestions in the testbed PR - Done
- Format all Java files with the google-java-format tool - Done

2024-08-19 19:26 UTC, lokiuox commented on community/detectors/xwiki_cve_2024_21650/src/test/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650DetectorTest.java
> +  }
Can you check the correctness of this test? It looks wrong to me, as by reading the code, it looks like when the callback server is not available, no findings should be returned. I think the issue here is stopping the callback server, as it seems it causes an exception that is not handled.

I'm running the tests with `./gradlew test --info --rerun-tasks`

2024-08-19 19:26 UTC, lokiuox commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650DetectorBootstrapModule.java
> +      return 3;
```suggestion
      return 10;
```

I think at least 10 seconds here is a safe bet, considering the network latency of a real environment and that the target may not respond quickly

2024-08-19 19:26 UTC, lokiuox commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650Detector.java
> +      "rest/wikis/xwiki/spaces/XWiki/pages/" + REQUEST_USER_NAME + "/objects/XWiki.XWikiUsers/0";
The decomposition is ok, what I mean is that e.g. the username and password are randomly generated and it's a bit counterintuitive for them to be "constants", and the same applies to other strings which includes the username and password. What about generating them inside the detection function and then replacing them like you're doing with the payload and token?

So, for instance, the `REQUEST_POST_DATA object would become something like:
```java
  private static final String REQUEST_POST_DATA =
      "parent=xwiki:Main.UserDirectory&register_first_name="
          + PAYLOAD_PLACEHOLDER
          + "&register_last_name=&xwikiname="
          + "{{USERNAME}}"
          + "&register_password="
          + "{{PASSWORD}}"
          + "&register2_password="
          + "{{PASSWORD}}"
          + "&register_email="
          + "&form_token={{TOKEN}}";
```

And the same would apply to `RESPONSE_STRING` and `REQUEST_CLEANUP_PATH`.

2024-08-19 19:29 UTC, lokiuox requested changes
Here are a few more comments on things to fix. Also, the `google-java-format` tool still tells me there are corrections to make (I'm using the jar version from the command line)

2024-08-21 18:00 UTC, YuriyPobezhymov commented on community/detectors/xwiki_cve_2024_21650/src/test/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650DetectorTest.java
> +  }
Ok, I found some problems around callback server usage. I fixed it through detector optimisation & tests improvement. Big changes there. I use spying of random values there, so I did revert mockito dependancy.
Now tests must work as expected.

2024-08-21 18:01 UTC, YuriyPobezhymov commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650DetectorBootstrapModule.java
> +      return 3;
Updated

2024-08-21 18:07 UTC, YuriyPobezhymov commented
I did global refactor to improve usage for the constants, now most of the related code are inside `isServiceVulnerable` method.
I made now google-java-format formatting through CLI, as you mentioned. Much better result.

2024-09-02 11:14 UTC, YuriyPobezhymov commented
Any updates @lokiuox?

2024-09-02 22:47 UTC, lokiuox requested changes
Hey @YuriyPobezhymov, I just added a few more comments on little things to address, and then it's good to go.

2024-09-02 22:47 UTC, lokiuox commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650Detector.java
> +import static java.nio.charset.StandardCharsets.UTF_8;
It would probably be better (on a stylistic level) to not import these fields statically. Rather, import their containing classes with a normal import. I know the code will be more verbose, but it will also be more explicit/clear.

2024-09-02 22:47 UTC, lokiuox commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650Detector.java
> +        return true;
When the detection is done with response matching when the callback server is not available, the behavior adopted by other plugins is to lower the severity to `HIGH` and add a line to the vulnerability description text to indicate how the vuln was detected.

e.g.:
- TCS is available and vuln was confirmed via callback:
> "The remote code execution was confirmed via an out-of-band callback"
- TCS is not available, vuln confirmed via response matching:
> "Since the Tsunami Callback Server was not available, the vulnerability was confirmed through response matching."

2024-09-02 22:47 UTC, lokiuox commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650Detector.java
> +    return Long.toHexString(Double.doubleToLongBits(Math.random()));
If you change this to:
```suggestion
    Random rand = new Random(this.utcClock.instant().toEpochMilli());
    return Long.toHexString(rand.nextLong());
```
you can avoid using `mock()` and `spy()` in the tests, as with the injected fake UTC clock this function would produce always the same value. It may also produce the same value in subsequent calls, but we probably don't really care.

Moreover, since this function is only used to get a pseudo-random username and password (to ensure that an account with that username doesn't exist I guess?), you could just use the millisecond time, with the same effect of not needing the extra imports in the tests:
```suggestion
    return Long.toHexString(this.utcClock.instant().toEpochMilli());
```

2024-09-02 22:47 UTC, lokiuox commented on community/detectors/xwiki_cve_2024_21650/src/test/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650DetectorTest.java
> +        .containsExactly(mock.buildDetectionReport(targetInfo, service));
> `mock.buildDetectionReport(targetInfo, service)`
I think it would probably be better to manually construct the `DetectionReport` object here instead of invoking the detector's own function, as a bug in that function would propagate here too and the tests would not detect it.

2024-09-02 22:47 UTC, lokiuox commented on community/detectors/xwiki_cve_2024_21650/src/test/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650DetectorTest.java
> +        .containsExactly(mock.buildDetectionReport(targetInfo, service));
> `mock.buildDetectionReport(targetInfo, service)`
I think it would probably be better to manually construct the `DetectionReport` object here instead of invoking the detector's own function, as a bug in that function would propagate here too and the tests would not detect it.

2024-09-02 22:47 UTC, lokiuox commented on community/detectors/xwiki_cve_2024_21650/src/test/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650DetectorTest.java
> +  }
I think you should split this test in two different tests for the negative cases too (whether the callback server is available or not), like you did with the positive cases.

2024-09-03 18:40 UTC, YuriyPobezhymov commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650Detector.java
> +import static java.nio.charset.StandardCharsets.UTF_8;
Done

2024-09-03 18:40 UTC, YuriyPobezhymov commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650Detector.java
> +    return Long.toHexString(Double.doubleToLongBits(Math.random()));
oh really, done.

2024-09-03 18:41 UTC, YuriyPobezhymov commented on community/detectors/xwiki_cve_2024_21650/src/test/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650DetectorTest.java
> +        .containsExactly(mock.buildDetectionReport(targetInfo, service));
changed

2024-09-03 18:41 UTC, YuriyPobezhymov commented on community/detectors/xwiki_cve_2024_21650/src/test/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650DetectorTest.java
> +  }
changed

2024-09-03 18:41 UTC, YuriyPobezhymov commented on community/detectors/xwiki_cve_2024_21650/src/test/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650DetectorTest.java
> +        .containsExactly(mock.buildDetectionReport(targetInfo, service));
changed

2024-09-03 18:53 UTC, YuriyPobezhymov commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650Detector.java
> +        return true;
Sorry, don't understand. Why severity becomes HIGH, when OOB server isn't available?
I did try to lookup other plugins for described behavior without success. Please provide more details about this part.
Where is located "vulnerability description text" - report, logs, readme etc?

2024-09-06 08:10 UTC, YuriyPobezhymov commented
@lokiuox, need some small additional explanation, thanks.

2024-09-20 09:19 UTC, YuriyPobezhymov commented
@maoning, @tooryx, @lokiuox - can we finish the PR in this quarter (till the end of October)?
It took too long for that, I can't take anything new for the plugin development.

Thank you for understanding, Yuriy.

2024-09-20 10:34 UTC, lokiuox commented
Hey @YuriyPobezhymov, sorry for the delay, I will try to finish the review later this week. Unfortunately there are many plugins under review and keeping up with all of them takes some time.

2024-09-23 15:06 UTC, lokiuox commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650Detector.java
> +        return true;
The logic is that when we can't confirm the RCE with 100% accuracy (i.e. with a callback) we lower the severity a bit.

Here's an instance where this was suggested by the Tsunami team: https://github.com/google/tsunami-security-scanner-plugins/pull/346#discussion_r1387901018 Since then there were other plugin like this and all have adopted the same behavior.

About the "vulnerability description", I mean the text you set with `setDescription()` in the vulnerability report.

2024-09-23 15:09 UTC, lokiuox commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650Detector.java
> +        return true;
@YuriyPobezhymov tag me if/when you push changes and I'll proceed with a new review.

2024-09-23 20:01 UTC, YuriyPobezhymov commented on community/detectors/xwiki_cve_2024_21650/src/main/java/com/google/tsunami/plugins/detectors/rce/cve202421650/Cve202421650Detector.java
> +        return true;
@lokiuox, I did add severity suggestion.
About the "vulnerability description" - I did implement this through `logger.atInfo().log`, that I found through research. I found plugin that do such way. Didn't found that in plugins `setDescription()`.

2024-09-23 21:34 UTC, lokiuox commented
Hi @YuriyPobezhymov, I did a final review and I think the plugin is fine. If possible, since the exploit requires multiple steps, please just add a few comments in the main `isServiceVulnerable` code to explain what each request is doing, so that the code is a bit more readable for people that aren't familiar with the vulnerability. After that, I'll mark the contribution as approved.

2024-09-24 12:19 UTC, YuriyPobezhymov commented
Hi @lokiuox, I did add comments.
Plse check for english spelling.

Thank you!

2024-09-24 13:10 UTC, lokiuox commented
LGTM - Approved
@maoning we can merge this and https://github.com/google/security-testbeds/pull/69

Reviewer: Savio, Doyensec
Plugin: XWiki User Registration RCE - CVE-2024-21650
Feedback: The overall quality of the contribution is very good. The plugin only needed minor stylistic improvements and some changes in the test cases. The fingerprinting and detection of the vulnerability are great. The testbed was good, needing only a small change to work; although instructions on how to perform the initial setup were missing. The contributor was very responsive.
Drawbacks: None.

2024-10-08 09:11 UTC, YuriyPobezhymov commented
@maoning, can me move forward?

2024-10-09 14:11 UTC, maoning commented
Yes, we will be merging this PR in the next 2-3 weeks.

2024-10-22 08:48 UTC, tooryx approved these changes

2024-10-23 11:27 UTC, merged