Add Craft CMS fingerprinter
google/tsunami-security-scanner-plugins pull request #434
Opened 2024-03-22 02:53 UTC by OccamsXor

Hey @tooryx @maoning,

Web application fingerprint for Craft CMS.

This PR includes the update script, docker-compose.yml, environment files, version files, and binproto file. I used two different environment and version files because they are required for different Craft CMS versions.

This is my first contribution to the project. Please let me know if there are any changes I should make. 

This resolves #406

2024-09-04 20:08 UTC, lokiuox requested changes
Hey @OccamsXor, thanks for your contribution!

I'm reviewing the fingerprinter and I've found some issues with it. I've already left some comments, but there are a few things which are a bit difficult to write in review comments, so here they are:

About the different files for version 3 and 4:
- Separating the environment variables in two files can be avoided, you can just put all the environment variables for versions 3 and 4 in the same environment file and each version will pick up the ones they use and ignore the others
- As a result, you can avoid having two different env files and two different versions.txt files


About the `update.sh` file:
The `CreateFingerprintForCraftCMS` function has several issues:
- Uses `curl` and `unzip` without checking if the commands are available, there's no guarantee that they are installed
- The `chown` command can only be run as root
- The entire procedure should really be done inside the container

Assuming that you join the contents of the two `.env` files in a single file called `env.txt` and the two versions files in a single file called `versions.txt`, here's an example on how to implement the Docker image correctly:

You can create a `Dockefile` that adds the required files at build time and sets the permissions correctly:
```Dockerfile
FROM craftcms/nginx:8.2-dev

ARG CRAFT_VERSION

USER root
RUN mkdir -p /app
WORKDIR /app
RUN wget "https://github.com/craftcms/cms/releases/download/${CRAFT_VERSION}/CraftCMS-${CRAFT_VERSION}.zip" -O CraftCMS.zip
RUN unzip -o CraftCMS.zip
COPY env.txt /app/.env
RUN chown -R www-data.www-data /app
USER www-data
```

Then modify the `docker-compose.yml` file to use the local Dockerfile instead of the craftcms image, passing the craftcms version from environment variables:
```yaml
  web:
    build: 
      context: .
      args:
        CRAFT_VERSION: "${CRAFT_VERSION}"
      ports:
        - 8080:8080
     ...
```

This way, the `update.sh` file can be greatly simplified, as the docker compose file can be used directly, without copying files around:
```sh
StartCraftCMS() {
  local version="$1"
  pushd "${APP_PATH}" >/dev/null
    CRAFT_VERSION="$version" docker compose up --build --wait -d
    docker exec -it craftcms-web-1 php craft install/craft --email test@test.com --username admin --password tsunami --site-name local --site-url http://localhost:8080 --language en-us
  popd >/dev/null
}

StopCraftCMS() {
  pushd "${APP_PATH}" >/dev/null
    docker compose down --volumes --remove-orphans
  popd >/dev/null
}

CreateFingerprintForCraftCMS(){
  local version="$1"
  StartCraftCMS "$version"
  checkOutRepo "${GIT_REPO}" "${version}"
  RESOURCES_PATH="${GIT_REPO}"
  updateFingerprint \
    "craftcms" \
    "${version}" \
    "${FINGERPRINTS_PATH}" \
    "${RESOURCES_PATH}" \
    "http://localhost:8080"
  StopCraftCMS
}
```
If you want you can just copy this code, I've verified that everything works as expected.

Also, please add the latest versions of CraftCMS to the version file.

2024-09-04 20:12 UTC, lokiuox commented on google/fingerprinters/web/scripts/updater/community/craftcms/update.sh
> +    docker-compose down --volumes --remove-orphans
```suggestion
    docker compose down --volumes --remove-orphans
```
Use new compose syntax

2024-11-07 11:40 UTC, lokiuox commented
Hi @OccamsXor, are you still interested in contributing to Tsunami with this plugin?

2024-12-28 19:03 UTC, lokiuox commented on google/fingerprinters/web/scripts/updater/community/craftcms/app/env
> +DISALLOW_ROBOTS=false
This way you can keep only one env file and not have to do differentiate between version 3 and the other ones.

```suggestion
# The application ID used to to uniquely store session and cache data, mutex locks, and more
CRAFT_APP_ID=
APP_ID=

# The environment Craft is currently running in (dev, staging, production, etc.)
CRAFT_ENVIRONMENT=production
ENVIRONMENT=production

# The secure key Craft will use for hashing and encrypting data
CRAFT_SECURITY_KEY=root
SECURITY_KEY=root

# Database connection settings
CRAFT_DB_DRIVER=mysql
DB_DRIVER=mysql
CRAFT_DB_SERVER=mysql
DB_SERVER=mysql
CRAFT_DB_PORT=3306
DB_PORT=3306
CRAFT_DB_DATABASE=dev_craftcms
DB_DATABASE=dev_craftcms
CRAFT_DB_USER=craftcms
DB_USER=craftcms
CRAFT_DB_PASSWORD=SecretPassword
DB_PASSWORD=SecretPassword
CRAFT_DB_SCHEMA=public
DB_SCHEMA=public
CRAFT_DB_TABLE_PREFIX=
DB_TABLE_PREFIX=

# General settings (see config/general.php)
DEV_MODE=false
ALLOW_ADMIN_CHANGES=false
DISALLOW_ROBOTS=false

CP_TRIGGER=admin
```

2024-12-28 19:03 UTC, lokiuox commented on google/fingerprinters/web/scripts/updater/community/craftcms/app/env_3
You can delete this

2024-12-28 19:04 UTC, lokiuox commented on google/fingerprinters/web/scripts/updater/community/craftcms/versions.txt
> +4.4.10
Merge versions into a single file

```suggestion
3.9.12
3.8.10
3.8.10.2
3.8.11
3.8.12
3.8.13
3.8.14
3.8.15
3.8.16
3.8.17
3.8.7
3.8.8
3.8.9
3.9.0
3.9.1
3.9.10
3.9.11
3.9.2
3.9.3
3.9.4
3.9.5
3.9.6
4.4.10
```

2024-12-28 19:04 UTC, lokiuox commented on google/fingerprinters/web/scripts/updater/community/craftcms/versions3.txt
You can delete this file

2024-12-28 19:08 UTC, lokiuox commented on google/fingerprinters/web/scripts/updater/community/craftcms/update.sh
> +done
No need to differentiate between the different versions now

```suggestion
# Read all released CraftCMS versions to be fingerprinted.
readarray -t ALL_VERSIONS < "${SCRIPT_PATH}/versions.txt"

for craftcms_version in "${ALL_VERSIONS[@]}"; do
  CreateFingerprintForCraftCMS "${craftcms_version}" "env"
done
```

2025-01-30 14:12 UTC, ikkisoft commented
@OccamsXor Do you have any updates on this? Given it's almost done, we would like to close this. Thanks!

2025-02-05 19:35 UTC, lokiuox requested changes
Hey @OccamsXor,

here are a few more fixes to apply.
Please also delete `env_3` and `versions3.txt` as they're no longer needed.

2025-02-06 15:59 UTC, lokiuox commented
LGTM - Approved
@maoning we can merge this.

Reviewer: Savio, Doyensec
Plugin: Craft CMS Fingerprinter
Drawbacks: None

2025-02-11 09:53 UTC, tooryx commented
Hi @OccamsXor,

This PR has been merged and the reward released.

_~tooryx_

2025-02-11 09:53 UTC, closed without merging