Updater script, asset files and also spark.binproto file added.
google/tsunami-security-scanner-plugins pull request #448
Opened 2024-04-02 09:56 UTC by VickyTheViking

Hi, dear tsunami team.
Apache Spark has different Web UI based on the way which it is ran. After hours of search I found a way to run it in the way that I can access all web UIs. So in this pull request we have:

1- Master web UI
2- Worker web UI
3- Web interface (Runs only when a SparkContext is running)

Which are extracted in one run of each version . I used apache/spark as base docker image, because it covered more versions than the official _/spark docker repo which naturally do not differ from each other. and versions without docker image were ignored.

2024-05-24 00:44 UTC, lokiuox commented
Hey @VickyTheViking, thanks for your contribution!

I'm reviewing your plugin but I've found that it's not working properly. Specifically, it looks like the fingerprinting for the main `8080` port is working, but not for the other two ports. I tried to do some quick troubleshooting, but I'm not familiar with Spark.

Here are the issues to fix:
- `update.sh` should be in be in the `spark/` folder, not `spark/app`
- `update.sh` should have the executable bit set
- The `spark-worker` container fails to start. Docker logs show the issue `ERROR Utils: Failed to create directory /opt/spark/work` which appears to be a permission issue. I was able to bypass it by adding `user: root` in the docker compose file, but I don't know if this is the correct way to fix such an issue. This seems to fix the issue with port `8081`.
- Nonetheless, the `docker exec` command fails, so the Python script is never executed and port `4040` remains unreachable.
- Also the selected Spark docker images do not seem to have Python at all, ensure they are the correct images.

Feel free to reach out.

~ Savio (Doyensec)

2024-07-08 17:54 UTC, lokiuox commented
Hey @VickyTheViking, thanks for the update, you still have to address the following issues:
- Set `user: root` in the docker compose file to fix the `spark-worker` container
- Fix the issue with the `docker exec` command failing

This is what I get when I try to manually reproduce the workflow and I launch the docker exec command:
```
$ docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:7077 /opt/spark/examples/src/main/python/fib.py
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark/jars/spark-unsafe_2.12-3.1.3.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
24/07/08 17:51:55 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.io.IOException: Cannot run program "python3": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at org.apache.spark.deploy.PythonRunner$.main(PythonRunner.scala:97)
	at org.apache.spark.deploy.PythonRunner.main(PythonRunner.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 16 more
log4j:WARN No appenders could be found for logger (org.apache.spark.util.ShutdownHookManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

2024-11-07 11:41 UTC, lokiuox commented
Hi @VickyTheViking, are you still interested in contributing to Tsunami with this plugin?

2024-12-15 21:27 UTC, lokiuox requested changes
Hey @VickyTheViking, thanks for the update. The fingerprinter seems to be working correctly now. I've left a few comments on a few small things that can be improved.

2024-12-15 21:27 UTC, lokiuox commented on google/fingerprinters/web/scripts/updater/community/spark/update.sh
> +      )
```suggestion
    if docker manifest inspect "apache/spark:${version}-python3" 2>/dev/null ; then
      SPARK_VERSION="${version}-python3" docker compose up -d
      sleep 10
    else
      SPARK_VERSION="${version}" docker compose up -d
      sleep 10
      echo -e "\nInstalling python3 into worker container"
      installPython3InSpark "${version}"
    fi
```

A more elegant way to do the same thing

2024-12-15 21:27 UTC, lokiuox commented on google/fingerprinters/web/scripts/updater/community/spark/update.sh
> +    docker exec  -it -u 0 spark-master pip3 install pyspark=="${version}" >/dev/null
```suggestion
    docker exec -it -u 0 spark-master apt-get update >/dev/null
    docker exec -it -u 0 spark-master apt-get install python3 python3-pip -y >/dev/null
    docker exec -it -u 0 spark-master pip3 install pyspark=="${version}" >/dev/null
```
`apt` is for interactive use, while `apt-get` is better suited for scripts

2024-12-15 21:27 UTC, lokiuox commented on google/fingerprinters/web/scripts/updater/community/spark/app/docker-compose.yml
> +      - SPARK_LOCAL_HOSTNAME=127.0.0.1
```suggestion
      - SPARK_LOCAL_HOSTNAME=127.0.0.1
      - DEBIAN_FRONTEND=noninteractive
```
Prevents interactive prompts

2024-12-28 18:45 UTC, lokiuox commented on google/fingerprinters/web/scripts/updater/community/spark/update.sh
> +      if g "apache/spark:${version}-python3" 2>/dev/null ; then
Hi @VickyTheViking , I think there was a typo or something similar here, as you can see the `docker manifest inspect` command was changed into a single `g`

2025-01-30 14:14 UTC, ikkisoft commented
@VickyTheViking Do you have any updates on this? Given it's almost done, we would like to close this. Thanks!

2025-02-05 18:23 UTC, lokiuox commented on google/fingerprinters/web/scripts/updater/community/spark/versions.txt
> +3.5.3
```suggestion
3.5.3
3.5.4
```

Hey @VickyTheViking, I just noticed there's a new version 3.5.4. Please apply the suggestion and I'll mark the contribution as good to go.

2025-02-12 13:19 UTC, closed without merging