DRAFT: Exposed spark UI and api
google/tsunami-security-scanner-plugins pull request #449
Opened 2024-04-02 21:36 UTC by timoles

@maoning this is the first part of the PR for https://github.com/google/tsunami-security-scanner-plugins/issues/416

The detector for the exposed WEB UI is missing. However, I though I first make sure everything is correct before adapting the detector for the exposed WEB UI. As the web ui is a simple http code check and regex, it should be less complex.

2024-04-02 21:37 UTC, timoles commented on community/detectors/rce/apache_spark_exposed_api/src/main/java/com/google/tsunami/plugins/detectors/rce/apachesparksexposedapi/ApacheSparksExposedApiVulnDetector.java
> +  // TODO change the following payload URI to the official Tsunami one
This is in here for testing purposes. We might want to merge the payload first and then this PR to ensure everything is working correctly.

2024-04-03 08:42 UTC, timoles commented
An additional remark: The RCE payload executes asynchronously and sometimes takes a few seconds to execute. In some instances the plugin queries the callback server before the payload had a chance to trigger the interaction. This leads to false-negatives. 

What is the usual approach for this issue? I assume implementing a sleep (as I did in testing) is not satisfactory. Can we have an asynchronous lookup for the payload at a later time?

2024-04-05 21:27 UTC, maoning commented
@timoles Yes, let's go with sleep for now. If you are interested in implementing an asynchronous lookup for the payload as part of payload generator framework, please let me know. I can make it as part of the patch reward. We will need to track all the interactions and finding templates from plugins that want to do asynchronous lookup and add an additional step before the scanner exits.

2024-04-05 21:54 UTC, maoning commented on payloads/community/apache_spark_exposed_api/Tsunami_Apache_Spark_Exploit.jar
For now, I can manually verify it. Could you separate this to a different PR, so that this can be merged in first for the plugin testing?

2024-04-08 20:48 UTC, timoles commented on community/detectors/rce/apache_spark_exposed_api/src/main/java/com/google/tsunami/plugins/detectors/rce/apachesparksexposedapi/ApacheSparksExposedApiVulnDetector.java
> +  // TODO change the following payload URI to the official Tsunami one
This can be changed as soon as #461 is merged

2024-04-08 20:48 UTC, timoles commented on payloads/community/apache_spark_exposed_api/Tsunami_Apache_Spark_Exploit.jar
Ah great. You can find the paylod in #461

2024-04-08 21:07 UTC, timoles commented
Both plugins (`exposed api to rce` and `web ui info disclosure`) are done and ready to review :) 

Thank you very much

2024-04-26 17:20 UTC, maoning commented on community/detectors/rce/apache_spark_exposed_api/src/main/java/com/google/tsunami/plugins/detectors/rce/apachesparksexposedapi/ApacheSparksExposedApiVulnDetector.java
> +  // TODO change the following payload URI to the official Tsunami one
It's now available at  https://github.com/google/tsunami-security-scanner-plugins/raw/master/payloads/apache_spark_exposed_api/Tsunami_Apache_Spark_Exploit.jar

2024-04-26 17:20 UTC, maoning commented on community/detectors/rce/apache_spark_exposed_api/src/main/java/com/google/tsunami/plugins/detectors/rce/apachesparksexposedapi/ApacheSparksExposedApiVulnDetector.java
> +    String finished_payload =
nit: camel case

2024-04-30 10:22 UTC, pisqu4red requested changes
Thank you for working on these plugins!

2024-04-30 10:22 UTC, pisqu4red commented on community/detectors/rce/apache_spark_exposed_api/src/main/java/com/google/tsunami/plugins/detectors/rce/apachesparksexposedapi/ApacheSparksExposedApiVulnDetector.java
> +  private static String interactionUriFormatString = "http://%s";
This prefixing is not needed - in fact, it doesn't work with it - it tries to fetch `http://http://<payload_server:port>/<path>`

2024-04-30 10:22 UTC, pisqu4red commented on community/detectors/apache_spark_exposed_webui/README.md
> +An Apache Spark Web Ui which is exposed to an attacker might disclose sensitive information to them. An attacker can retrieve information such as the configured workers and master node within the Apa
nit: s/envrionment/environment/

2024-04-30 21:18 UTC, timoles commented on community/detectors/rce/apache_spark_exposed_api/src/main/java/com/google/tsunami/plugins/detectors/rce/apachesparksexposedapi/ApacheSparksExposedApiVulnDetector.java
> +  // TODO change the following payload URI to the official Tsunami one
done

2024-04-30 21:22 UTC, timoles commented
I resolved all open issues. However, there appear some build issues due to `com.google.guava`. As far as I can tell this issue appeared recently, for my and other plugins. Is there some dependency issue?

2024-05-02 13:58 UTC, pisqu4red commented
Correct, @timoles - please sync with master. We have upgraded gradle to 7.0 in [this commit](https://github.com/google/tsunami-security-scanner-plugins/commit/08ee18d51e03cf6c1b62c1ed1b01343c35b46bad) so this should resolve the last failures.

2024-05-13 09:32 UTC, pisqu4red approved these changes

2024-05-13 20:30 UTC, merged

2024-05-15 11:25 UTC, pisqu4red commented
Hi @timoles,

Your PR has been merged. This usually means a reward will be granted. Google will start the internal QC process and the reward amount will be determined based on the quality of the detector report. Please be patient and allow up to a week for the QC process to finish. You'll be notified once the decision is made.

Thanks!