CVE-2022-29165 Argo CD Auth Bypass, publicly exposed UI with admin access
google/tsunami-security-scanner-plugins pull request #452
Opened 2024-04-04 16:55 UTC by JamesFoxxx

Hi, it is related to my PRP https://github.com/google/tsunami-security-scanner-plugins/issues/431.

2024-04-08 03:30 UTC, JamesFoxxx commented
@maoning I found a way to execute RCE, it needs to deploy payload on an arbitrary path on any Git server like Github! I tried a simple HTTP and HTTPS server to serve the git repo but it doesn't work.
what should I do, If I can put payloads in this repo we can validate the vulnerability with RCE.

2024-04-11 20:33 UTC, maoning commented
@JamesFoxxx I'm testing out github payload hosting with this other plugin: https://github.com/google/tsunami-security-scanner-plugins/pull/449 

You can also add your payload in the same /payloads directory, and open a separate PR for it, so that I can merge it in first.

2024-04-25 23:10 UTC, maoning commented
https://github.com/google/tsunami-security-scanner-plugins/pull/467 for the payload (for tracking purpose)

2024-04-26 20:11 UTC, JamesFoxxx commented
@maoning I'll improve this PR to check with a RCE callback instead of simple response checking this week.

2024-05-14 20:42 UTC, JamesFoxxx commented
@maoning please merge these PRs first: 
https://github.com/google/security-testbeds/pull/43
https://github.com/google/security-testbeds/pull/42
This PR https://github.com/google/tsunami-security-scanner-plugins/pull/472 is important because after merge I should update the payload location in source code based on this repository URL.

PR is ready for review :) the test cases are not comprehensive yet, I'll add more test cases, please review the plugin first and till then I will find time to add more test cases.

2024-05-22 18:58 UTC, JamesFoxxx commented
apologize for the delay, it was a hard journey for me, I had to analyze a CVE with no public PoC, plus I had to find a way to disable authentication. after that, I upgraded the plugin to get an OOB confirmation.  (I'll be happy if you can consider a bonus for this submission because I'm comparing this to most of the other bounty submissions)
Best regards, James.

@maoning @tooryx

2024-05-23 15:13 UTC, lokiuox requested changes
Hi @JamesFoxxx, thank you for your contribution!
I reviewed your plugin with the latest changes, (including https://github.com/google/security-testbeds/pull/43 and https://github.com/google/security-testbeds/pull/42) and I confirm that it works, although I left some comments on a few things that can be improved.

Please also remember to run the [google-java-format](https://github.com/google/google-java-format) tool before submitting the changes to ensure that the code is properly formatted.

Moreover, I also left some comments on the testbed PRs:

- https://github.com/google/security-testbeds/pull/43#pullrequestreview-2074173457
- https://github.com/google/security-testbeds/pull/42#pullrequestreview-2074199721

To recap, the following things need to be done before this submission can be be merged:

- [ ] Address the comments in this review
- [ ] Address the comments in the testbed PRs
- [ ] The testbed PRs need to be merged
- [ ] #472 needs to be merged and the URL updated in the code

Feel free to reach out.

~ Savio (Doyensec)

2024-05-23 15:13 UTC, lokiuox commented on community/detectors/argocd_exposed_ui/src/test/java/com/google/tsunami/plugins/detectors/exposedui/argocd/ExposedArgoCDDetectorTest.java
> +import com.google.inject.util.Modules;
Remove unused import.

2024-05-24 08:27 UTC, JamesFoxxx commented
@lokiuox I wanted to apply one more update, I changed the phrase "argo cd instances" to "argo cd API server" in the namings and descriptions because the documentation explicitly says "Access The Argo CD API Server" in [here](https://argo-cd.readthedocs.io/en/stable/getting_started/#3-access-the-argo-cd-api-server). Also, the instances in argo cd should be related to application instances, so it was some kind of wrong naming that I did before.

2024-05-24 15:49 UTC, JamesFoxxx commented
@lokiuox please note that the guice injection for sleep duration is completely copied from this recently merged PR https://github.com/google/tsunami-security-scanner-plugins/pull/456

2024-05-24 16:33 UTC, lokiuox requested changes
It looks like the plugin is working correctly!

I left you some comments about a few minor things to fix, but I'd say the plugin is almost ready to be merged.

Please also fix the following things:
- Align all file names to one naming scheme (the one you prefer):
  -  `Cve202017526DetectorConfigs.java` still has the name of the plugin it was copied from
  - `ExposedArgoCdApiDetectorBootstrapModule.java` follows the new naming with `Api` in the name
  - `ExposedArgoCdDetector.java` and `ExposedArgoCdDetectorTest.java` follow the old naming
- Also left you one more comment on the setup README for the vulnerable version: https://github.com/google/security-testbeds/pull/43#pullrequestreview-2077348496

2024-05-25 16:50 UTC, lokiuox requested changes
Hey @JamesFoxxx, the exception text is still printed due to `withCause(e)` being still present.

I also did some more tests, and I realized that the string and the exception are printed even when scanning completely unrelated applications, which doesn't really make sense. I checked the implementations of other plugins, and I noticed that all of them just return false in case the target isn't vulnerable, without logging anything, so I suggest you to do the same here and just return without printing anything. I also commented on two more logged strings that I think should be deleted for the same reason.

Please also remember to run the [google-java-format](https://github.com/google/google-java-format) before submitting the changes. :)

2024-05-25 16:50 UTC, lokiuox commented on community/detectors/argocd_exposed_ui/src/main/java/com/google/tsunami/plugins/detectors/exposedui/argocd/ExposedArgoCdApiDetector.java
> +        logger.atWarning().withCause(e).log("The application does not appear to be vulnerable");
Consider removing this line

2024-05-25 16:50 UTC, lokiuox commented on community/detectors/argocd_exposed_ui/src/main/java/com/google/tsunami/plugins/detectors/exposedui/argocd/ExposedArgoCdApiDetector.java
> +        logger.atWarning().withCause(e).log("The application does not appear to be vulnerable");
Consider removing this line

2024-05-25 16:50 UTC, lokiuox commented on community/detectors/argocd_exposed_ui/src/main/java/com/google/tsunami/plugins/detectors/exposedui/argocd/ExposedArgoCdApiDetector.java
> +    logger.atInfo().log("targetUri is %s", targetUri);
Consider removing this line, since sent HTTP requests are already logged by default

2024-05-25 16:50 UTC, lokiuox commented on community/detectors/argocd_exposed_ui/src/main/java/com/google/tsunami/plugins/detectors/exposedui/argocd/ExposedArgoCdApiDetector.java
> +      logger.atInfo().log("the response is %s", response);
Consider removing this line, as it's too verbose and the status code of HTTP responses is already logged by default

2024-05-25 17:23 UTC, lokiuox approved these changes

2024-05-25 17:24 UTC, JamesFoxxx commented
@lokiuox I'm sorry about this loggin issue, I shoud've tested your last review before pushing it here.

2024-06-26 06:30 UTC, JamesFoxxx commented
I'm curious to know if there is any particular priority system or logical method applied when sorting the pull requests for review and merging. this pull request was reviewed one month ago by the Dyonsec team and before that I waited nearly two months to start reviewing, I'm curious because some contributors merged more than 2 PRs during this time, is there any priority between the products?  it is 4 months :)) that I've been waiting to merge this PR 
CC: @tooryx and @maoning

2024-07-31 14:23 UTC, tooryx commented
Hey @JamesFoxxx,

Sorry. We generally try to go with first-come, first reviewed, but it seems we have not been making a good job there.
I will work on getting this merged.

_~tooryx_

2024-08-05 15:44 UTC, merged