Mlflow weak credential tester
google/tsunami-security-scanner-plugins pull request #455
Opened 2024-04-06 00:52 UTC by lanced00m

https://github.com/google/tsunami-security-scanner-plugins/issues/412

Hi @maoning 
I couldn't test the plugin on a vulnerable target because of this error:
```bash
Apr 06, 2024 4:43:41 AM com.google.tsunami.workflow.DefaultScanningWorkflow runAsync
INFO: Staring Tsunami scanning workflow.
Apr 06, 2024 4:43:41 AM com.google.tsunami.workflow.DefaultScanningWorkflow fingerprintNetworkServices
INFO: Port scanning phase done, moving to service fingerprinting phase with '0' fingerprinter(s) selected.
Apr 06, 2024 4:43:41 AM com.google.tsunami.main.cli.TsunamiCli main
SEVERE: Exiting due to workflow execution exceptions.
java.util.concurrent.ExecutionException: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.IllegalAccessError: class com.google.tsunami.plugins.detectors.credentials.genericweakcredentialdetector.proto.ServiceDefaultCredentials tried to access method 'com.google.protobuf.LazyStringArrayList com.google.protobuf.LazyStringArrayList.emptyList()' (com.google.tsunami.plugins.detectors.credentials.genericweakcredentialdetector.proto.ServiceDefaultCredentials and com.google.protobuf.LazyStringArrayList are in unnamed module of loader 'app')

```

but I'm sure it works because of the Comprehensive test cases I've implemented. 

what I'm doing is simply running `./gradlew build` in `google/detectors/credentials/generic_weak_credential_detector` directory and then I copy the Nmap plugin to `/google/detectors/credentials/generic_weak_credential_detector/build/libs/` because it is needed.
finally, I run this command:

```bash
java -cp "tsunami-main-0.0.22-SNAPSHOT-cli.jar:/absolute/path/to/tsunami-security-scanner-plugins/google/detectors/credentials/generic_weak_credential_detector/build/libs/*" com.google.tsunami.main.cli.TsunamiCli --uri-target=http://127.0.0.1:5000
```
I'm working with `openjdk-11`.

2024-04-15 13:02 UTC, pisqu4red requested changes
Thanks for your pull request. Please review the comments.

Regarding failure to build - did you follow instructions for setup in [README of the main Tsunami repo](https://github.com/google/tsunami-security-scanner?tab=readme-ov-file#quick-start)? Particularly, what is the - `gradle --version`? We need 6.5 for building Tsunami.

2024-04-30 12:21 UTC, pisqu4red commented
@lanced00m could you please sync with master branch? 

We have upgraded gradle to 7.0 in [this commit](https://github.com/google/tsunami-security-scanner-plugins/commit/08ee18d51e03cf6c1b62c1ed1b01343c35b46bad) so this should resolve the last failures.

The reason for asking for the `gradle --version` command is that it gives other information about the JVM and OS environment as well. 

Could you please address my previous comments before doing another round of review. Thanks!

2024-04-30 15:11 UTC, lanced00m commented
@pisqu4red Sorry I didn't understand fully your last comment.
I updated the branch and I tested the compilation now and the `./gradlew compile` worked fine.
should I still show you the `gradle --version` output? because my problem is solved.
I double-checked the first round of reviews and I applied the changes, do you mean that I should mark the comments as resolved in this pull request?
Also, I'm sorry I put all the changes in one commit so from diff, it seems that it is really hard to compare the code, I'll revert the additional spaces now so I hope it gets better.

2024-04-30 15:19 UTC, lanced00m commented
@pisqu4red Now you can compare the initial commit with the last commit easier `0de8e9a581b994cce339d60f1743c17b3e2c8d30`.
I'm going to add one more commit to add proper spaces too.

2024-05-13 09:28 UTC, pisqu4red requested changes
Thanks for the changes, small nitpicks from my side before we merge.

2024-05-13 12:12 UTC, pisqu4red commented on google/detectors/credentials/generic_weak_credential_detector/src/main/java/com/google/tsunami/plugins/detectors/credentials/genericweakcredentialdetector/testers/mlflow/MlFlowCredentialTester.java
> +                        + "#authenticating-to-mlflow"
Missing space at the end of this string, causes `detect_canAccept` test to fail.

2024-05-13 17:45 UTC, merged

2024-05-15 11:25 UTC, pisqu4red commented
Hi @lanced00m,

Your PR has been merged. This usually means a reward will be granted. Google will start the internal QC process and the reward amount will be determined based on the quality of the detector report. Please be patient and allow up to a week for the QC process to finish. You'll be notified once the decision is made.

Thanks!