Zenml weak credentials
google/tsunami-security-scanner-plugins pull request #491
Opened 2024-05-27 22:15 UTC by secureness

PRP: https://github.com/google/tsunami-security-scanner-plugins/issues/444
testbeds: https://github.com/google/security-testbeds/pull/57

2024-06-11 12:13 UTC, leonardo-doyensec reviewed
Hello @secureness.
Thank you for your contribution. There are several issues to address. You can find all of them in the comments.

Feel free to reach out.
~ Leonardo (Doyensec)

2024-06-12 12:49 UTC, leonardo-doyensec commented on google/detectors/credentials/generic_weak_credential_detector/src/main/resources/detectors/credentials/genericweakcredentialdetector/data/service_default_credentials.textproto
> +}
Perfect. This was not clear at the beginning. After running Tsunami with the fingerprint plugin, everything works fine on my side.

2024-06-25 08:15 UTC, pisqu4red requested changes

2024-06-25 08:15 UTC, pisqu4red commented on google/detectors/credentials/generic_weak_credential_detector/src/main/java/com/google/tsunami/plugins/detectors/credentials/genericweakcredentialdetector/testers/zenml/ZenMlCredentialTester.java
> +    logger.atWarning().log(
We have test breaking on our side:

error: [FloggerLogString] Arguments to log(String) must be compile-time constants or parameters annotated with @CompileTimeConstant. If possible, use Flogger's formatting log methods instead.

2024-06-25 11:50 UTC, merged

2024-07-29 11:32 UTC, tooryx commented
Hey @secureness, I will check with the rest of the team.