Slurm Exposed REST API Detector
google/tsunami-security-scanner-plugins pull request #496
Opened 2024-06-06 07:39 UTC by lanced00m

https://github.com/google/tsunami-security-scanner-plugins/issues/423

I wrote this plugin based on [this](https://github.com/google/tsunami-security-scanner-plugins/pull/451) which has been merged recently with minimal changes as many as possible.

2024-11-26 22:24 UTC, lokiuox requested changes
Hey @lanced00m, thank you for your contribution!

I'm reviewing your plugin and I confirm it works correctly. I left a few comments on things that could be improved. Also, please update the first message with the link of the new testbed PR (https://github.com/google/security-testbeds/pull/98)

2024-11-26 22:24 UTC, lokiuox commented on community/detectors/slurm_exposed_rest_api/src/test/java/com/google/tsunami/plugins/detectors/rce/SlurmExposedRestApiDaemonVuLnDetectorTest.java
> +  private void startMockWebServer(boolean withAnExistingModel) throws IOException {
The `withAnExistingModel` argument is never used, please remove it

2024-11-26 22:24 UTC, lokiuox commented on community/detectors/slurm_exposed_rest_api/src/test/java/com/google/tsunami/plugins/detectors/rce/SlurmExposedRestApiDaemonVuLnDetectorTest.java
> +                  && request.getBody().readString(StandardCharsets.UTF_8).isEmpty()) {
```suggestion
            if (Objects.equals(request.getPath(), "/openapi/v3")
                && request.getMethod().equals("GET")
                && request.getBody().readString(StandardCharsets.UTF_8).isEmpty()) {
```
You can AND these conditions instead of using nested ifs

2024-11-26 22:24 UTC, lokiuox commented on community/detectors/slurm_exposed_rest_api/src/test/java/com/google/tsunami/plugins/detectors/rce/SlurmExposedRestApiDaemonVuLnDetectorTest.java
> +              if (request.getMethod().equals("POST")
```suggestion
            if (request.getPath().matches("/slurm/v0\\.0\\.\\d\\d/job/submit")
                && request.getMethod().equals("POST")
```
You can AND these conditions instead of using nested ifs

2024-11-26 22:24 UTC, lokiuox commented on community/detectors/slurm_exposed_rest_api/src/test/java/com/google/tsunami/plugins/detectors/rce/SlurmExposedRestApiDaemonVuLnDetectorTest.java
> +    mockTargetService.url("/");
```suggestion
```
Not needed

2024-11-26 22:24 UTC, lokiuox commented on community/detectors/slurm_exposed_rest_api/src/test/java/com/google/tsunami/plugins/detectors/rce/SlurmExposedRestApiDaemonVuLnDetectorTest.java
> +    Truth.assertThat(mockCallbackServer.getRequestCount()).isEqualTo(1);
```suggestion
   assertThat(mockTargetService.getRequestCount()).isEqualTo(2);
   assertThat(mockCallbackServer.getRequestCount()).isEqualTo(1);
```
Be consistent with the others usages of `assertThat`

2024-11-26 22:24 UTC, lokiuox commented on community/detectors/slurm_exposed_rest_api/src/test/java/com/google/tsunami/plugins/detectors/rce/SlurmExposedRestApiDaemonVuLnDetectorTest.java
> +    Truth.assertThat(mockTargetService.getRequestCount()).isEqualTo(2);
```suggestion
   assertThat(mockTargetService.getRequestCount()).isEqualTo(2);
```
Be consistent with the others usages of `assertThat`

2024-11-27 16:55 UTC, lanced00m commented
@lokiuox, thank you for your comprehensive review! All issues are solved now, so you can check the PR again.

2024-11-28 01:37 UTC, lokiuox requested changes
Hey @lanced00m, here's just a few more minor things to fix, then the plugin's good to go.

2024-11-28 01:37 UTC, lokiuox commented on community/detectors/slurm_exposed_rest_api/src/main/java/com/google/tsunami/plugins/detectors/rce/SlurmExposedRestApiDetector.java
> +                        + "therefore execute arbitrary OS-level commands on slurm compute nodes")
```suggestion
                    "An exposed Slurm REST API server can be exploited by attackers to submit a job and "
                        + "therefore execute arbitrary OS-level commands on Slurm compute nodes")
```
Capitalization and better wording

2025-02-12 12:11 UTC, merged