PRP: GeoServer Unauthenticated Remote Code Execution
google/tsunami-security-scanner-plugins pull request #522
Opened 2024-08-03 20:57 UTC by grandsilva

2024-09-02 18:58 UTC, lokiuox commented
Hey @grandsilva, I've checked your commits and they look ok, but the `detect_whenVulnerable_returnsVulnerability` test fails. I think it's because of the new version detection step, so please make sure to account for that in the tests too.

2024-09-21 18:47 UTC, lokiuox requested changes
Hey @grandsilva, the plugin looks good. I've left comments on two small things to fix, then it's good to go. 

Also, please make sure to run the google-java-format tool before pushing new changes (the command-line version is preferred).

2024-09-21 18:47 UTC, lokiuox commented on community/detectors/geoserver_cve_2024_36401/src/main/java/com/google/tsunami/plugins/detectors/rce/GeoserverCve202436401VulnDetector.java
> +                .filter(this::isGeoserverInstance)
```suggestion
            matchedServices.stream()
                .filter(NetworkServiceUtils::isWebService)
                .filter(this::isGeoserverInstance)
```

Just to be safe, let's filter for web services as the first step.

2024-09-21 18:47 UTC, lokiuox commented on community/detectors/geoserver_cve_2024_36401/src/test/java/com/google/tsunami/plugins/detectors/rce/GeoserverCve202436401VulnDetectorTest.java
> +    Truth.assertThat(mockTargetService.getRequestCount()).isEqualTo(1);
```suggestion
    Truth.assertThat(mockTargetService.getRequestCount()).isEqualTo(2);
```
You missed this in the last commit

2024-09-23 16:33 UTC, lokiuox requested changes
Hey @grandsilva, I cannot push to your branch as I do not have write access to it, but there were just a few changes so I put them here as review suggestions so you can auto-apply them.

2024-09-23 16:33 UTC, lokiuox commented on community/detectors/geoserver_cve_2024_36401/src/main/java/com/google/tsunami/plugins/detectors/rce/GeoserverCve202436401VulnDetector.java
> +import com.google.tsunami.plugin.payload.PayloadGenerator;
```suggestion
import com.google.tsunami.plugin.payload.Payload;
import com.google.tsunami.plugin.payload.PayloadGenerator;
import com.google.tsunami.plugins.detectors.rce.Annotations.OobSleepDuration;
```
Reorder imports

2024-09-23 16:33 UTC, lokiuox commented on community/detectors/geoserver_cve_2024_36401/src/main/java/com/google/tsunami/plugins/detectors/rce/GeoserverCve202436401VulnDetector.java
> +import com.google.tsunami.common.net.http.HttpClient;
```suggestion
import com.google.tsunami.common.data.NetworkServiceUtils;
import com.google.tsunami.common.net.http.HttpClient;
```
Add import for NetworkServiceUtils

2024-09-23 16:33 UTC, lokiuox commented on community/detectors/geoserver_cve_2024_36401/src/main/java/com/google/tsunami/plugins/detectors/rce/GeoserverCve202436401VulnDetector.java
> +                    "Upgrade Geoserver to a patched version. The vulnerability was fixed in versions 2.23.6, 2.24.4, and 2.25.2.")
```suggestion
                    "Upgrade Geoserver to a patched version. The vulnerability was fixed in"
                        + " versions 2.23.6, 2.24.4, and 2.25.2.")
```
Split overlong line

2024-09-23 16:33 UTC, lokiuox commented on community/detectors/geoserver_cve_2024_36401/src/test/java/com/google/tsunami/plugins/detectors/rce/GeoserverCve202436401VulnDetectorTest.java
> +import com.google.tsunami.plugin.payload.testing.PayloadTestHelper;
```suggestion
import com.google.tsunami.plugin.payload.testing.PayloadTestHelper;
import com.google.tsunami.plugins.detectors.rce.Annotations.OobSleepDuration;
```
Reorder imports

2024-09-23 16:33 UTC, lokiuox commented on community/detectors/geoserver_cve_2024_36401/src/test/java/com/google/tsunami/plugins/detectors/rce/GeoserverCve202436401VulnDetectorTest.java
> +                            "Upgrade Geoserver to a patched version. The vulnerability was fixed in versions 2.23.6, 2.24.4, and 2.25.2.")
```suggestion
                        .setDescription(
                            "This detector checks for Geoserver RCE (CVE-2024-36401). Multiple OGC"
                                + " request parameters allow Remote Code Execution (RCE) by"
                                + " unauthenticated users through specially crafted input against a"
                                + " default GeoServer installation due to unsafely evaluating"
                                + " property names as XPath expressions.")
                        .setRecommendation(
                            "Upgrade Geoserver to a patched version. The vulnerability was fixed in"
                                + " versions 2.23.6, 2.24.4, and 2.25.2.")
```
Split overlong strings

2024-09-23 17:13 UTC, lokiuox commented
LGTM - Approved
@maoning we can merge this and https://github.com/google/security-testbeds/pull/79

Reviewer: Savio, Doyensec
Plugin: GeoServer Unauthenticated RCE - CVE-2024-36401
Feedback: The overall quality of the contribution is very good. The plugin only lacked a fingerprinting step, but the implementation quality was high; the text description could have been improved a bit, too. The testbed was a bit too complex and could be simplified. The contributor was very responsive.

2024-10-22 12:20 UTC, tooryx approved these changes

2024-10-22 12:39 UTC, tooryx commented
Hi @grandsilva,

This PR is currently in internal review and should be merge in a few days.

~tooryx

2024-10-23 08:50 UTC, merged