Joomla Improper AccessCheck in WebService Endpoint
google/tsunami-security-scanner-plugins pull request #529
Opened 2024-08-29 07:38 UTC by am0o0

hi, the testbed PR: https://github.com/google/security-testbeds/pull/92
and the Tsunami PRP issue:  https://github.com/google/tsunami-security-scanner-plugins/issues/276

2024-10-03 12:54 UTC, leonardo-doyensec commented
Hello @am0o0. Thank you for your contribution. In order to be compliant with the standard, please open a PR containing  the testbed on the https://github.com/google/security-testbeds repository.

2024-10-25 19:10 UTC, lokiuox requested changes
Hi @am0o0,

Thank you for your contribution! 

I'm reviewing your plugin and I think it's ok and, while I appreciate your extra effort, I think it would be better if, after leaking the credentials, the detector did not attempt to log into the app or try to determine if the DB is public or not. What if a user gets kicked/locked out or a DB is marked as not publicly accessible while it actually is or vice-versa? I'd say it would be better to limit the "responsibilities" of the detector and keep it as simple as possible.

Therefore I think the best course of actions would be to just dump the raw response in the additional details section of the report without adding anything else, and let the final user investigate on the finding.

2024-10-25 19:10 UTC, lokiuox commented on community/detectors/joomla_cve_2023_23752/src/main/java/com/google/tsunami/plugins/detectors/cves/cve202323752/Cve202323752VulnDetector.java
> +                .setRecommendation("Upgrade to version 4.2.8 and higher")
```suggestion
                .setRecommendation("Upgrade Joomla to a supported version.")
```

2024-10-25 19:10 UTC, lokiuox commented on community/detectors/joomla_cve_2023_23752/src/main/java/com/google/tsunami/plugins/detectors/cves/cve202323752/Cve202323752VulnDetector.java
> +                        + " webservice endpoints. attacker can get critical information of database and webserver like passwords by this vulnerability")
```suggestion
                .setTitle("Joomla unauthorized access to webservice endpoints")
                .setDescription(
                    "CVE-2023-23752: An improper access check allows unauthorized access to"
                        + " webservice endpoints. attacker can get critical information of database and webserver like passwords by this vulnerability")
```
I think this description is a bit generic. From the web I found that DB credentials could be exposed by this finding, but are there any other credentials that could be exposed too? If not, let's just explicitly say that DB creds could be exposed.

2024-10-25 19:10 UTC, lokiuox commented on community/detectors/joomla_cve_2023_23752/src/main/java/com/google/tsunami/plugins/detectors/cves/cve202323752/Cve202323752DetectorBootstrapModule.java
> + * Copyright 2022 Google LLC
```suggestion
 * Copyright 2024 Google LLC
```

2024-10-25 19:10 UTC, lokiuox commented on community/detectors/joomla_cve_2023_23752/src/main/java/com/google/tsunami/plugins/detectors/cves/cve202323752/Cve202323752VulnDetector.java
> + * Copyright 2020 Google LLC
```suggestion
 * Copyright 2024 Google LLC
```

2024-11-21 19:31 UTC, lokiuox requested changes
Hey @am0o0, the plugins looks good and I verified it works. I've left some comments on a few minor improvements. Thanks!

2024-11-21 19:31 UTC, lokiuox commented on community/detectors/joomla_cve_2023_23752/src/test/java/com/google/tsunami/plugins/detectors/cves/cve202323752/Cve202323752VulnDetectorTest.java
> +  private static final String LeakedDataJsonSample =
```suggestion
  private static final String LEAKED_DATA_JSON_SAMPLE =
```
Follow Google's style guide for constants

2024-11-21 19:31 UTC, lokiuox commented on community/detectors/joomla_cve_2023_23752/src/test/java/com/google/tsunami/plugins/detectors/cves/cve202323752/Cve202323752VulnDetectorTest.java
> +  public void DetectCVE202323752() {
```suggestion
  public void detect_whenVulnerable_returnsVulnerability() {
```
Follow style for test names

2024-11-21 19:31 UTC, lokiuox commented on community/detectors/joomla_cve_2023_23752/src/test/java/com/google/tsunami/plugins/detectors/cves/cve202323752/Cve202323752VulnDetectorTest.java
> +    assert (mockWebServerDetectionReports.getDetectionReportsList().isEmpty());
```suggestion
    assertThat(mockWebServerDetectionReports.getDetectionReportsList()).isEmpty();
```
Use `assertThat` instead of `assert`

2024-11-21 19:31 UTC, lokiuox commented on community/detectors/joomla_cve_2023_23752/src/main/java/com/google/tsunami/plugins/detectors/cves/cve202323752/Cve202323752VulnDetector.java
> +    } catch (IllegalStateException | JsonSyntaxException | IOException | AssertionError e) {
```suggestion
    } catch (NoSuchElementException | IllegalStateException | JsonSyntaxException e) {
      return false;
    } catch (IOException e) {
```
JSON errors should be catched in a different block so we can return silently in case the target we're scanning is not actually a Joomla instance or is patched.

2024-11-21 19:31 UTC, lokiuox commented on community/detectors/joomla_cve_2023_23752/src/main/java/com/google/tsunami/plugins/detectors/cves/cve202323752/Cve202323752VulnDetector.java
> +      }
```suggestion
      // Check if body values match our detection rules
      if (!appConfHttpResponse.bodyString().get().contains("password")
              || !appConfHttpResponse.bodyString().get().contains("user")) {
        return false;
      }

      // Check if body is JSON
      if (appConfHttpResponse.bodyJson().isEmpty()) {
        return false;
      }

      JsonObject jsonResponse = appConfHttpResponse.bodyJson().get().getAsJsonObject();
      if (!jsonResponse.has("data")) {
        return false;
      }

      JsonArray jsonArray = jsonResponse.getAsJsonArray("data");
      for (int i = 0; i < jsonArray.size(); i++) {
        if (jsonArray.get(i).getAsJsonObject().has("attributes")) {
          exposedConfig = appConfHttpResponse.bodyString().get();
          return true;
        }
      }
```
We can use a "early-return" pattern instead of nested ifs here

2024-11-25 19:12 UTC, lokiuox approved these changes
LGTM - Approved
@maoning we can merge this and https://github.com/google/security-testbeds/pull/92

Reviewer: Savio, Doyensec
Plugin: Joomla Improper AccessCheck in WebService Endpoint - CVE-2023-23752
Drawbacks: None.

2024-11-27 13:06 UTC, tooryx approved these changes

2024-11-27 20:53 UTC, merged