add detect plugin GoAnywhere MFT RCE (CVE-2023-0669)
google/tsunami-security-scanner-plugins pull request #541
Opened 2024-10-02 09:13 UTC by SuperX-SIR

Hey,

this PR for the Vuln Detector Plugin for issue: https://github.com/google/tsunami-security-scanner-plugins/issues/540

Add instructions to create the test environment https://github.com/google/security-testbeds/pull/90

2025-02-27 21:50 UTC, savio-doyensec requested changes
Hi @SuperX-SIR, thanks for your contribution! 
I've left some comments on a few things that can be improved.

Please also remember to do the following:
- Sync the latest commits from the master branch
- Run the `google-java-format` tool

2025-02-27 21:50 UTC, savio-doyensec commented on community/detectors/goanywhere_cve_2023_0669/src/main/java/com/google/tsunami/plugins/detectors/goanywhere/Cve20230669VulnDetector.java
> +      logger.atInfo().log("Callback server disabled but required for this detector.");
```suggestion
      logger.atWarning().log("Callback server disabled but required for this detector.");
```
Let's make this a warning so it stands out a bit more

2025-02-27 21:50 UTC, savio-doyensec commented on community/detectors/goanywhere_cve_2023_0669/src/main/java/com/google/tsunami/plugins/detectors/goanywhere/Cve20230669VulnDetector.java
> +              networkService);
```suggestion
              networkService);
      Uninterruptibles.sleepUninterruptibly(Duration.ofSeconds(3));
```
Add some sleep time here just in case

2025-02-27 21:50 UTC, savio-doyensec commented on community/detectors/goanywhere_cve_2023_0669/src/test/java/com/google/tsunami/plugins/detectors/goanywhere/Cve20230669DetectorWithCallbackServerTest.java
> +    mockWebServer.enqueue(new MockResponse().setResponseCode(HttpStatus.OK.code()));
```suggestion
    mockWebServer.enqueue(new MockResponse().setResponseCode(HttpStatus.OK.code()).setBody("<title>GoAnywhere 6.8.6</title>"));
    mockWebServer.enqueue(new MockResponse().setResponseCode(HttpStatus.OK.code()));
```
Add mock request for fingerprinting step

2025-02-27 21:50 UTC, savio-doyensec commented on community/detectors/goanywhere_cve_2023_0669/src/test/java/com/google/tsunami/plugins/detectors/goanywhere/Cve20230669DetectorWithCallbackServerTest.java
> +                                + "provides a fix 7.1.2 or later"))
```suggestion
                            .setDescription(
                                    "GoAnywhere MFT suffers from a pre-authentication command injection "
                                            + "vulnerability in the License Response Servlet due to deserializing"
                                            + " an arbitrary attacker-controlled object. All versions prior to 7.1.1 are affected.")
                            .setRecommendation(
                                    "Update GoAnywhere MFT to version 7.1.2 or later."))
```
Align Description and Recommendation to the ones in the detector code

2025-03-11 21:57 UTC, savio-doyensec commented
Hi @SuperX-SIR, I noticed you haven't added the fingerprinting step from the last review, please add it. Also make sure to run the `google-java-format` tool; the command line version is preferable.

2025-03-20 12:15 UTC, savio-doyensec commented
@SuperX-SIR Are you still interested in contributing? We're using a trial license to test this detector, and once it expires it may become difficult for us to do the final review and consequently approve this contribution.

2025-03-21 15:47 UTC, SuperX-SIR commented
> @SuperX-SIR Are you still interested in contributing? We're using a trial license to test this detector, and once it expires it may become difficult for us to do the final review and consequently approve this contribution.

Yep, I am contributing

2025-03-24 18:41 UTC, savio-doyensec commented
Hi @SuperX-SIR , unfortunately the fingerprint check you have implemented is not working for me (using the testbed you supplied). 

Please fix it or just add the check I suggested in the previous review, as that one was already verified to work:
- https://github.com/google/tsunami-security-scanner-plugins/pull/541#discussion_r1974286237
- https://github.com/google/tsunami-security-scanner-plugins/pull/541#discussion_r1974286800
- https://github.com/google/tsunami-security-scanner-plugins/pull/541#discussion_r1974383451

Please note that unfortunately we have only a few days until our license expires.

2025-03-25 17:22 UTC, SuperX-SIR commented
> t or just add the check I suggested in the previous review, as that one was already verified to work:

Apologies for my oversight. The commit I submitted earlier was not thoroughly tested.

I have made the modifications based on your feedback and validated them in my local environment.

One question remains: I’m unclear why there is a connection error in the local testing environment (this does not affect the plugin’s successful detection of the vulnerability).

The log and config file results are as follows:
0. vulnerability target
http://192.168.1.9:38000/

1. callback server: ip 192.168.1.3

```
java -cp "tcs-main-0.0.1-SNAPSHOT-cli.jar" \
  com.google.tsunami.callbackserver.main.TcsMain \
  --custom-config=tcs_config.yaml
```

tcs_config.yaml
```
common:
  domain: cb.tsunami       # Doesn't matter in http callback mode
  external_ip: 192.168.1.3   # Running it locally
storage:
  in_memory:
    interaction_ttl_secs: 43200  # 12 hours
    cleanup_interval_secs: 3600  # 1 hour
recording:
  http:
    port: 8881                   # Any port available on the local machine
    worker_pool_size: 2
polling:
  port: 8880
  worker_pool_size: 2
```

logfile: 
```
Mar 25, 2025 1:19:17 PM com.google.tsunami.callbackserver.main.TcsMain main
INFO: Starting the server with these flags: [--custom-config=tcs_config.yaml]
Mar 25, 2025 1:19:17 PM com.google.tsunami.callbackserver.server.common.HttpServer start
INFO: HTTP server HttpRecordingServer started on port 8881.
Mar 25, 2025 1:19:17 PM com.google.tsunami.callbackserver.server.common.HttpServer start
INFO: HTTP server InteractionPollingServer started on port 8880.
Mar 25, 2025 1:19:26 PM com.google.tsunami.callbackserver.server.common.RequestLogger logRequestAndGetClientAddr
INFO: Received HTTP request on RECORDING endpoint from IP 192.168.1.9: HttpObjectAggregator$AggregatedFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(ridx: 0, widx: 0, cap: 0, components=0))
GET /54771b0b0fefb728cdd26d7181fdf883e4c2b1a220096a477c7b4cef HTTP/1.1
Host: 192.168.1.3:8881
User-Agent: curl/7.61.1
Accept: */*
content-length: 0
Mar 25, 2025 1:19:26 PM com.google.tsunami.callbackserver.server.recording.HttpRecordingHandler lambda$handleRequest$1
INFO: Recording HTTP interaction with CBID '54771b0b0fefb728cdd26d7181fdf883e4c2b1a220096a477c7b4cef' from IP 192.168.1.9
Mar 25, 2025 1:19:26 PM com.google.tsunami.callbackserver.server.common.RequestLogger logRequestAndGetClientAddr
INFO: Received HTTP request on POLLING endpoint from IP 192.168.1.3: HttpObjectAggregator$AggregatedFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(ridx: 0, widx: 0, cap: 0, components=0))
GET /?secret=e3b60c94a49b8036 HTTP/1.1
Cache-Control: no-cache
User-Agent: TsunamiSecurityScanner
Host: 192.168.1.3:8880
Connection: Keep-Alive
Accept-Encoding: gzip
content-length: 0
Mar 25, 2025 1:19:26 PM com.google.tsunami.callbackserver.server.polling.InteractionPollingHandler handleRequest
INFO: Interaction with secret 'e3b60c94a49b8036' found and polled by IP 192.168.1.3
```

2. tsunami-main-0.0.24-SNAPSHOT-cli.jar 

```
  java -cp "tsunami-main-0.0.24-SNAPSHOT-cli.jar:/home/kali/tsunami/plugins/*" \
  -Dtsunami-config.location=/home/kali/tsunami/tsunami.yaml \
  com.google.tsunami.main.cli.TsunamiCli \
  --uri-target=http://192.168.1.9:38000/\
  --callback-address=192.168.1.3 \
  --callback-port=8881 \
  --callback-polling-uri=http://192.168.1.3:8880  \
  --scan-results-local-output-format=JSON \
  --scan-results-local-output-filename=/tmp/tsunami-output_3.json
Mar 25, 2025 1:08:30 PM com.google.tsunami.main.cli.TsunamiCli main
INFO: Full classpath scan took 4.618 s
Mar 25, 2025 1:08:30 PM com.google.tsunami.common.config.ConfigModule configure
INFO: Found Tsunami config class: com.google.tsunami.common.net.http.HttpClientConfigProperties
Mar 25, 2025 1:08:30 PM com.google.tsunami.common.config.ConfigModule configure
INFO: Found Tsunami config class: com.google.tsunami.plugin.TcsConfigProperties
Mar 25, 2025 1:08:30 PM com.google.tsunami.common.config.ConfigModule configure
INFO: Found Tsunami config class: com.google.tsunami.plugins.portscan.nmap.NmapPortScannerConfigs
Mar 25, 2025 1:08:30 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.common.io.archiving.GoogleCloudStorageArchiver$Options
Mar 25, 2025 1:08:30 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.common.net.http.HttpClientCliOptions
Mar 25, 2025 1:08:30 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.main.cli.LanguageServerOptions
Mar 25, 2025 1:08:30 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.main.cli.ScanResultsArchiver$Options
Mar 25, 2025 1:08:30 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.main.cli.option.MainCliOptions
Mar 25, 2025 1:08:30 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.plugin.TcsClientCliOptions
Mar 25, 2025 1:08:30 PM com.google.tsunami.common.cli.CliOptionsModule configure
INFO: Found CliOption: com.google.tsunami.plugins.portscan.nmap.option.NmapPortScannerCliOptions
Mar 25, 2025 1:08:31 PM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.detectors.goanywhere.Cve20230669VulnDetector
Mar 25, 2025 1:08:31 PM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.detectors.goanywhere.Cve20230669VulnDetector is registered.
Mar 25, 2025 1:08:31 PM com.google.tsunami.plugin.PluginLoadingModule configure
INFO: Found plugin class: com.google.tsunami.plugins.portscan.nmap.NmapPortScanner
Mar 25, 2025 1:08:31 PM com.google.tsunami.plugin.PluginBootstrapModule registerPlugin
INFO: Plugin class com.google.tsunami.plugins.portscan.nmap.NmapPortScanner is registered.
Mar 25, 2025 1:08:31 PM com.google.tsunami.main.cli.TsunamiCli run
INFO: TsunamiCli starting...
Mar 25, 2025 1:08:31 PM com.google.tsunami.main.cli.server.RemoteServerLoader runServerProcesses
INFO: Starting language server processes (if any)...
Mar 25, 2025 1:08:31 PM com.google.tsunami.workflow.DefaultScanningWorkflow runAsync
INFO: Staring Tsunami scanning workflow.
Mar 25, 2025 1:08:31 PM com.google.tsunami.workflow.DefaultScanningWorkflow fingerprintNetworkServices
INFO: Port scanning phase done, moving to service fingerprinting phase with '0' fingerprinter(s) selected.
Mar 25, 2025 1:08:31 PM com.google.tsunami.workflow.DefaultScanningWorkflow detectVulnerabilities
INFO: Service fingerprinting phase done, moving to vuln detection phase.
Mar 25, 2025 1:08:31 PM com.google.tsunami.plugins.detectors.goanywhere.Cve20230669VulnDetector detect
INFO: CVE-2023-0669 starts detecting.
Mar 25, 2025 1:08:31 PM com.google.tsunami.common.net.http.OkHttpHttpClient send
INFO: Sending HTTP 'GET' request to 'http://192.168.1.9:38000/'.
Mar 25, 2025 1:08:31 PM com.google.tsunami.common.net.http.OkHttpHttpClient parseResponse
INFO: Received HTTP response with code '200' for request to 'http://192.168.1.9:38000/goanywhere/auth/Login.xhtml'.
Mar 25, 2025 1:08:31 PM com.google.tsunami.plugin.payload.Payload getPayload
INFO: vulnerability_type: BLIND_RCE
interpretation_environment: LINUX_SHELL
execution_environment: EXEC_INTERPRETATION_ENVIRONMENT
 generated payload `curl http://192.168.1.3:8881/3a13b8fb86193fffc1518f5fbc324387fe5976ab9440fa1547ebb528`, does use the callback server
Mar 25, 2025 1:08:31 PM com.google.tsunami.common.net.http.OkHttpHttpClient send
INFO: Sending HTTP 'POST' request to 'http://192.168.1.9:38000/goanywhere/lic/accept'.
Mar 25, 2025 1:08:31 PM com.google.tsunami.common.net.http.OkHttpHttpClient parseResponse
INFO: Received HTTP response with code '200' for request to 'http://192.168.1.9:38000/goanywhere/lic/a [...]

2025-03-25 19:08 UTC, savio-doyensec requested changes
Hey @SuperX-SIR, that's fine, sometimes that happens when the vulnerable program being exploited doesn't reply to the HTTP request and closes the connection. Since this is ok in our case, we can just catch that specific exception so it the scanner doesn't log it. I also moved the sleep just before the check so that it's executed regardless of the exception happening.

You should be able to simply apply the two suggestions here. I confirm everything works fine.

2025-03-25 19:08 UTC, savio-doyensec commented on community/detectors/goanywhere_cve_2023_0669/src/main/java/com/google/tsunami/plugins/detectors/goanywhere/Cve20230669VulnDetector.java
> +    return payload.checkIfExecuted();
```suggestion
    } catch (EOFException e) {
      // This is expected, don't print an error
    } catch (IOException e) {
      logger.atWarning().withCause(e).log("Request to target %s failed", networkService);
    }
    Uninterruptibles.sleepUninterruptibly(Duration.ofSeconds(3));
    return payload.checkIfExecuted();
```

2025-03-25 19:08 UTC, savio-doyensec commented on community/detectors/goanywhere_cve_2023_0669/src/test/java/com/google/tsunami/plugins/detectors/goanywhere/Cve20230669DetectorWithCallbackServerTest.java
> +    mockWebServer.enqueue(new MockResponse().setResponseCode(HttpStatus.OK.code()));*/
```suggestion
```
Remove unused code

2025-03-26 01:56 UTC, SuperX-SIR commented on community/detectors/goanywhere_cve_2023_0669/src/test/java/com/google/tsunami/plugins/detectors/goanywhere/Cve20230669DetectorWithCallbackServerTest.java
> +    mockWebServer.enqueue(new MockResponse().setResponseCode(HttpStatus.OK.code()));*/
Thank you for your guidance. I have made the modifications and completed the testing, and the results perfectly meet expectations.

2025-03-26 17:39 UTC, savio-doyensec approved these changes
LGTM - Approved
@maoning, this can be merged alongside with https://github.com/google/security-testbeds/pull/90

Reviewer: Savio, Doyensec
Plugin: CVE-2023-0669

2025-04-27 07:09 UTC, SuperX-SIR commented
@maoning 
Is there any update

2025-07-09 16:27 UTC, tooryx commented
Hi @SuperX-SIR,

Sorry for the delay. This change has been approved and will be merged in a few hours/days.

_~tooryx_

2025-07-09 17:21 UTC, merged