AI PRP: AutoGPT RCE detector
google/tsunami-security-scanner-plugins pull request #546
Opened 2024-11-02 10:45 UTC by am0o0

Hi @tooryx, Sorry for the delay, and thanks for your patience! :)
https://github.com/google/tsunami-security-scanner-plugins/issues/536
https://github.com/google/security-testbeds/pull/96

2024-12-04 13:55 UTC, giacomo-doyensec commented
Hello @Amo0o0, thanks for your contribution!

I’ve verified that the plugin generally works but I’d like to point out some improvements / edge cases ;
1. The plugin lacks a fingerprint detection phase, please check whether the service is an AutoGPT instance before sending the payload, this is to avoid sending the payload to all the web services that the scanner encounter.
2. The detection works only if the AutoGPT service is in a “clean state” (it’s not processing other requests), can you develop a workaround for this?
3. In the detect phase check if responses are consistent before sending the next one, if they aren’t return an error. I had multiple time-out or fails in detection due to the plugin assuming that the second and third request returned 200. This is related to (2).
4. Ensure to run the `google-java-format` tool (statements should be <=100 chars and the test code imports some unused libraries)
5. I think that the `return false` at `ExposedAutoGptApiDetector.java#166` inside the `catch` statement is redundant as the next line would be executed anyway

2024-12-04 18:12 UTC, giacomo-doyensec requested changes
Thank you for the quick reply!

It looks like the detector is working correctly now, I just added some changes to conform to Google's Java format.

2024-12-05 09:37 UTC, giacomo-doyensec commented
**LGTM** - Approved
@maoning we can merge this and https://github.com/google/security-testbeds/pull/96

_Reviewer_: Giacomo, Doyensec
_Plugin_: CVE-2024-6091 -  AutoGPT RCE

2025-07-18 22:25 UTC, merged

2025-07-18 22:28 UTC, maoning commented
Hi @am0o0,

Your PR has been merged. This usually means a reward will be granted. Google will start the internal QC process and the reward amount will be determined based on the quality of the detector report. Please be patient and allow up to a week for the QC process to finish. You'll be notified once the decision is made.

Thanks!