AI PRP: localai CVE-2024-2029 RCE
google/tsunami-security-scanner-plugins pull request #558
Opened 2024-12-05 11:06 UTC by devampkid

Hii
I wrote this plugin after my request got approved here: https://github.com/google/tsunami-security-scanner-plugins/issues/554

the testbed: https://github.com/google/security-testbeds/pull/100

2024-12-10 15:41 UTC, giacomo-doyensec requested changes
Hello @devampkid, thanks for your contribution!
Below, you’ll find a few issues to address, along with some suggestions. Please ensure that you run the `google-java-format` tool on all files before submitting the updated version.

2024-12-10 15:41 UTC, giacomo-doyensec commented on community/detectors/localai_cve_2024_2029/src/main/java/com/google/tsunami/plugins/detectors/rce/cve20242029/LocalAiCve20242029RceDetector.java
> +  private boolean isServiceVulnerable(NetworkService networkService) {
Please rewrite this function, you can use `HttpClient` to build the request without manually crafting it, this is both for better readability and code robustness.

2024-12-10 15:41 UTC, giacomo-doyensec commented on community/detectors/localai_cve_2024_2029/src/main/java/com/google/tsunami/plugins/detectors/rce/cve20242029/LocalAiCve20242029RceDetector.java
> +          Resources.toByteArray(Resources.getResource(this.getClass(), "simpleAudio.ogg")));
Please verify https://github.com/google/security-testbeds/pull/100#discussion_r1877922125 and then simplify the detection accordingly if possible.

```suggestion
```

2024-12-10 15:41 UTC, giacomo-doyensec commented on community/detectors/localai_cve_2024_2029/src/main/resources/com/google/tsunami/plugins/detectors/rce/cve20242029/simpleAudio.ogg
Please, remove this file if it's not needed.

2024-12-12 16:08 UTC, giacomo-doyensec reviewed
Hello @devampkid, thanks for the updates! 
I left a couple of comments about improvements that can be applied down below.

2024-12-13 12:46 UTC, giacomo-doyensec requested changes
Hello @devampkid,
here you can find some minor style issues to address, then the plugin should be ok.
Thank you!

2024-12-13 12:46 UTC, giacomo-doyensec commented on community/detectors/localai_cve_2024_2029/src/main/java/com/google/tsunami/plugins/detectors/rce/cve20242029/LocalAiCve20242029RceDetector.java
> +import com.google.tsunami.plugin.payload.Payload;
Please remove unused imports.
```suggestion
```

2024-12-13 12:46 UTC, giacomo-doyensec commented on community/detectors/localai_cve_2024_2029/src/test/java/com/google/tsunami/plugins/detectors/rce/cve20242029/LocalAiCve20242029RceDetectorTest.java
> +import org.junit.Test;
```suggestion
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;
```

2024-12-13 12:46 UTC, giacomo-doyensec commented on community/detectors/localai_cve_2024_2029/src/test/java/com/google/tsunami/plugins/detectors/rce/cve20242029/LocalAiCve20242029RceDetectorTest.java
> +                                + "v1/audio/transcriptions endpoint."))
```suggestion
                                + " Remote Code Execution Vulnerability. Attackers can inject"
                                + " arbitrary OS commands within the audio filename filed during"
                                + " uploading the audio file with a POST HTTP request and send it"
                                + " to the v1/audio/transcriptions endpoint."))
```

2024-12-13 12:46 UTC, giacomo-doyensec commented on community/detectors/localai_cve_2024_2029/src/test/java/com/google/tsunami/plugins/detectors/rce/cve20242029/LocalAiCve20242029RceDetectorTest.java
> +                            "LocalAI user should upgrade the LocalAI to the versions v2.10.0 and above.")
```suggestion
                            "LocalAI user should upgrade the LocalAI to the versions v2.10.0 and"
                                + " above.")
```

2024-12-13 17:26 UTC, giacomo-doyensec commented on community/detectors/localai_cve_2024_2029/src/main/java/com/google/tsunami/plugins/detectors/rce/cve20242029/LocalAiCve20242029RceDetector.java
> +    }
Thanks @devampkid!
This check is not needed anymore, please remove it, then we should be good to go.

2024-12-14 10:28 UTC, giacomo-doyensec commented
**LGTM** - Approved 
@maoning we can merge this and https://github.com/google/security-testbeds/pull/100

_Reviewer_: Giacomo, Doyensec 
_Plugin_: CVE-2024-2029 - LocalAI

2025-02-18 08:02 UTC, tooryx commented
Hi @devampkid,

Sorry for the delay, we are processing requests in chronological order. Please bear with us!

_~tooryx_

2025-07-19 00:28 UTC, maoning commented on community/detectors/localai_cve_2024_2029/src/test/java/com/google/tsunami/plugins/detectors/rce/cve20242029/LocalAiCve20242029RceDetectorTest.java
> +  private void startMockWebServerForTestingWithOob(boolean mustHaveForgedCookie)
@devampkid mustHaveForgedCookie is not used in this method, do you remember what was it intended for?

2025-07-19 08:07 UTC, devampkid commented
@maoning, it was copied and pasted from the base plugin. Now I have removed it from the tests.

2025-07-22 01:02 UTC, maoning commented
Hi @devampkid,

Your PR has been merged. This usually means a reward will be granted. Google will start the internal QC process and the reward amount will be determined based on the quality of the detector report. Please be patient and allow up to a week for the QC process to finish. You'll be notified once the decision is made.

Thanks!

2025-07-22 08:26 UTC, devampkid commented
@maoning, should we close this PR since it has been merged, but the PR is still open.

2025-07-22 21:15 UTC, closed without merging